const sprueche = [
  // ---------------------------------------------------------
  // 1-50: NEUANFANG & AKTION
  // ---------------------------------------------------------
  { text: "Jeder Tag ist eine neue Chance, deine Geschichte neu zu schreiben.", kat: "Neuanfang & Aktion" },
  { text: "Dein einziger Limit bist du selbst – spreng die Grenzen!", kat: "Neuanfang & Aktion" },
  { text: "Der beste Zeitpunkt anzufangen war gestern. Der zweitbeste ist JETZT.", kat: "Neuanfang & Aktion" },
  { text: "Kleine Schritte jeden Tag führen zu riesigen Erfolgen.", kat: "Neuanfang & Aktion" },
  { text: "Vergleiche dich nur mit der Person, die du gestern warst.", kat: "Neuanfang & Aktion" },
  { text: "Aus Mut gemacht: Wer riskiert, kann gewinnen.", kat: "Neuanfang & Aktion" },
  { text: "Steh auf, richte deine Krone und geh weiter.", kat: "Neuanfang & Aktion" },
  { text: "Dein Potenzial ist unendlich – hör auf, dich klein zu machen.", kat: "Neuanfang & Aktion" },
  { text: "Erfolg beginnt im Kopf, Durchhaltevermögen im Herzen.", kat: "Neuanfang & Aktion" },
  { text: "Heute ist der Tag, an dem du deiner Zukunft danken wirst.", kat: "Neuanfang & Aktion" },
  { text: "Warte nicht auf den perfekten Moment, nimm den Moment und mach ihn perfekt.", kat: "Neuanfang & Aktion" },
  { text: "Starte dort, wo du stehst. Nutze, was du hast. Tue, was du kannst.", kat: "Neuanfang & Aktion" },
  { text: "Zweifel töten mehr Träume als Versagen es jemals könnte.", kat: "Neuanfang & Aktion" },
  { text: "Mach heute etwas, worauf du morgen stolz sein kannst.", kat: "Neuanfang & Aktion" },
  { text: "Der erste Schritt ist immer der schwerste, aber er führt ans Ziel.", kat: "Neuanfang & Aktion" },
  { text: "Wer keine Fehler macht, macht wahrscheinlich gar nichts.", kat: "Neuanfang & Aktion" },
  { text: "Verwandle deine Wünsche in konkrete Ziele.", kat: "Neuanfang & Aktion" },
  { text: "Du musst nicht großartig starten, aber du musst starten, um großartig zu werden.", kat: "Neuanfang & Aktion" },
  { text: "Heute ist ein großartiger Tag für einen Neuanfang.", kat: "Neuanfang & Aktion" },
  { text: "Setze dir Tore und laufe, bis du sie erreichst.", kat: "Neuanfang & Aktion" },
  { text: "Ein Jahr von heute an wirst du dir wünschen, du hättest heute angefangen.", kat: "Neuanfang & Aktion" },
  { text: "Aktion besiegt Angst.", kat: "Neuanfang & Aktion" },
  { text: "Lass deine Taten lauter sprechen als deine Worte.", kat: "Neuanfang & Aktion" },
  { text: "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.", kat: "Neuanfang & Aktion" },
  { text: "Es gibt keinen Aufzug zum Erfolg – du musst die Treppe nehmen.", kat: "Neuanfang & Aktion" },
  { text: "Jedes Hindernis ist ein Wegweiser in Richtung Wachstum.", kat: "Neuanfang & Aktion" },
  { text: "Breche den alten Trott auf und mach Raum für Neues.", kat: "Neuanfang & Aktion" },
  { text: "Aus Ausreden werden niemals Ergebnisse.", kat: "Neuanfang & Aktion" },
  { text: "Sei die Veränderung, die du in deiner Welt sehen willst.", kat: "Neuanfang & Aktion" },
  { text: "Mut bedeutet nicht die Abwesenheit von Angst, sondern das Handeln trotz ihr.", kat: "Neuanfang & Aktion" },
  { text: "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.", kat: "Neuanfang & Aktion" },
  { text: "Du bist der Regisseur deines eigenen Lebens.", kat: "Neuanfang & Aktion" },
  { text: "Geh den Extra-Kilometer, dort ist es nie überfüllt.", kat: "Neuanfang & Aktion" },
  { text: "Taten erschaffen Fakten.", kat: "Neuanfang & Aktion" },
  { text: "Der Unterschied zwischen Träumen und Erreichen ist Disziplin.", kat: "Neuanfang & Aktion" },
  { text: "Beginne den Tag mit einer klaren Absicht.", kat: "Neuanfang & Aktion" },
  { text: "Verlasse deine Komfortzone – dort geschieht die Magie.", kat: "Neuanfang & Aktion" },
  { text: "Mach deinen Erfolg unumgänglich.", kat: "Neuanfang & Aktion" },
  { text: "Heute investierst du in die Person, die du morgen bist.", kat: "Neuanfang & Aktion" },
  { text: "Setze dein Fundament Stein für Stein.", kat: "Neuanfang & Aktion" },
  { text: "Die beste Zeit für Veränderungen ist genau in diesem Augenblick.", kat: "Neuanfang & Aktion" },
  { text: "Richte deinen Blick nach vorne und geh los.", kat: "Neuanfang & Aktion" },
  { text: "Hör auf zu träumen, fang an zu bauen.", kat: "Neuanfang & Aktion" },
  { text: "Aus Versuchen entstehen Möglichkeiten.", kat: "Neuanfang & Aktion" },
  { text: "Glaube an den Prozess, auch wenn das Ziel noch fern scheint.", kat: "Neuanfang & Aktion" },
  { text: "Ein Funke Tatenkraft wiegt mehr als ein Ozean voller Absichten.", kat: "Neuanfang & Aktion" },
  { text: "Greif nach den Sternen, selbst wenn du stolperst, landest du oben.", kat: "Neuanfang & Aktion" },
  { text: "Lass dich nicht vom Tempo anderer verunsichern.", kat: "Neuanfang & Aktion" },
  { text: "Entscheide dich täglich neu für deine Träume.", kat: "Neuanfang & Aktion" },
  { text: "Dein Wille bestimmt deine Richtung.", kat: "Neuanfang & Aktion" },

  // ---------------------------------------------------------
  // 51-100: ENERGIE & POWER
  // ---------------------------------------------------------
  { text: "Lass deine Energie sprechen, bevor du ein Wort sagst.", kat: "Energie & Power" },
  { text: "Vollgas voraus! Es gibt keine Hindernisse, nur Herausforderungen.", kat: "Energie & Power" },
  { text: "Brenne für deine Träume, bis sie Realität werden.", kat: "Energie & Power" },
  { text: "Deine Energie zieht deine Zukunft an – halte sie hoch!", kat: "Energie & Power" },
  { text: "Nicht warten, bis der Sturm vorbeizieht – lerne im Regen zu tanzen.", kat: "Energie & Power" },
  { text: "Energie folgt dem Fokus: Richte deinen Blick auf das Ziel.", kat: "Energie & Power" },
  { text: "Lade deine Akkus mit positiven Gedanken und leg los.", kat: "Energie & Power" },
  { text: "Du bist ein Kraftwerk voller Ideen und Tatendrang.", kat: "Energie & Power" },
  { text: "Mach deine Zweifel stumm und deine Taten laut.", kat: "Energie & Power" },
  { text: "Kein Hindernis ist zu hoch, wenn dein Wille stark genug ist.", kat: "Energie & Power" },
  { text: "Lass dich von deiner Leidenschaft antreiben.", kat: "Energie & Power" },
  { text: "Spüre die Kraft, die in jedem neuen Moment steckt.", kat: "Energie & Power" },
  { text: "Stecke alle mit deiner Begeisterung an.", kat: "Energie & Power" },
  { text: "Gib jedem Tag die Chance, dein persönlich bester zu werden.", kat: "Energie & Power" },
  { text: "Volle Kraft voraus auf deine Ziele zu.", kat: "Energie & Power" },
  { text: "Power entsteht aus der Entscheidung, niemals aufzugeben.", kat: "Energie & Power" },
  { text: "Transformiere Stress in reine Handlungsenergie.", kat: "Energie & Power" },
  { text: "Sei ein Magnet für positive Ergebnisse.", kat: "Energie & Power" },
  { text: "Energie lässt sich nicht stoppen, nur lenken.", kat: "Energie & Power" },
  { text: "Mit der richtigen Einstellung gibt es keine Grenzen.", kat: "Energie & Power" },
  { text: "Nimm dir den Raum, den du brauchst, um zu strahlen.", kat: "Energie & Power" },
  { text: "Deine Schwingung bestimmt deine Ausstrahlung.", kat: "Energie & Power" },
  { text: "Fülle deinen Geist mit Zuversicht.", kat: "Energie & Power" },
  { text: "In dir steckt mehr Kraft, als du dir vorstellst.", kat: "Energie & Power" },
  { text: "Aktiviere deine innere Stärke und marschiere los.", kat: "Energie & Power" },
  { text: "Wer brennt, muss keine Angst vor der Kälte haben.", kat: "Energie & Power" },
  { text: "Schüttel den Staub ab und starte durch.", kat: "Energie & Power" },
  { text: "Mach deine Energie zu deiner Visitenkarte.", kat: "Energie & Power" },
  { text: "Lass dich von Barrieren nicht bremsen, sondern katapultieren.", kat: "Energie & Power" },
  { text: "Adrenalin und Fokus bilden dein bestes Werkzeug.", kat: "Energie & Power" },
  { text: "Du bist der Kapitän deines Schiffs – nimm das Steuer fest in die Hand.", kat: "Energie & Power" },
  { text: "Lebe mit Intensität und Hingabe.", kat: "Energie & Power" },
  { text: "Gedanken kreieren Realität – denke stark!", kat: "Energie & Power" },
  { text: "Fokus auf das Positivste bringt die meiste Kraft.", kat: "Energie & Power" },
  { text: "Setze neue Standards für dein Energieniveau.", kat: "Energie & Power" },
  { text: "Sei unaufhaltsam in deinem Streben.", kat: "Energie & Power" },
  { text: "Bring deine Ideen mit voller Wucht auf die Straße.", kat: "Energie & Power" },
  { text: "Dynamik entsteht durch stetige Bewegung.", kat: "Energie & Power" },
  { text: "Tanke Zuversicht und starte die Motoren.", kat: "Energie & Power" },
  { text: "Aus Begeisterung wächst unerschöpfliche Ausdauer.", kat: "Energie & Power" },
  { text: "Die eigene Überzeugung ist der stärkste Treibstoff.", kat: "Energie & Power" },
  { text: "Bleib unter Strom und setze Zeichen.", kat: "Energie & Power" },
  { text: "Jeder Puls ist eine Erinnerung an dein Potenzial.", kat: "Energie & Power" },
  { text: "Deine Leidenschaft ist dein persönlicher Turbolader.", kat: "Energie & Power" },
  { text: "Schaffe Ergebnisse, die deine kühnsten Erwartungen übertreffen.", kat: "Energie & Power" },
  { text: "Lass den inneren Funken zum Flächenbrand werden.", kat: "Energie & Power" },
  { text: "Power ist keine Frage des Glücks, sondern der Haltung.", kat: "Energie & Power" },
  { text: "Leuchte so hell, dass Zweifel im Schatten verschwinden.", kat: "Energie & Power" },
  { text: "Überwinde den Trägheitsmoment – danach wird alles leichter.", kat: "Energie & Power" },
  { text: "Deine Energie zeigt den Weg.", kat: "Energie & Power" },

  // ---------------------------------------------------------
  // 101-150: IDEEN & KREATIVITÄT
  // ---------------------------------------------------------
  { text: "Große Ideen beginnen oft mit einem mutigen Gedanken.", kat: "Ideen & Kreativität" },
  { text: "Denke nicht outside the box – denk so, als gäbe es gar keine Box.", kat: "Ideen & Kreativität" },
  { text: "Jeder Experte war einmal ein Anfänger. Trau dich!", kat: "Ideen & Kreativität" },
  { text: "Kreativität ist Intelligenz, die Spaß hat.", kat: "Ideen & Kreativität" },
  { text: "Probieren geht über Studieren: Mach deine Idee sichtbar.", kat: "Ideen & Kreativität" },
  { text: "Aus Fehlern entstehen oft die besten Erfindungen.", kat: "Ideen & Kreativität" },
  { text: "Hab keine Angst vor verrückten Ideen – sie verändern die Welt.", kat: "Ideen & Kreativität" },
  { text: "Schreib deine Visionen auf und erwecke sie zum Leben.", kat: "Ideen & Kreativität" },
  { text: "Erfinde dich täglich neu und bleibe neugierig.", kat: "Ideen & Kreativität" },
  { text: "Verwandle Herausforderungen in deine nächsten Meisterwerke.", kat: "Ideen & Kreativität" },
  { text: "Ein unbeschriebenes Blatt ist die Leinwand deiner Möglichkeiten.", kat: "Ideen & Kreativität" },
  { text: "Kreative Köpfe suchen Lösungen, wo andere Grenzen sehen.", kat: "Ideen & Kreativität" },
  { text: "Inspiration findet dich beim Arbeiten, nicht beim Warten.", kat: "Ideen & Kreativität" },
  { text: "Deine Fantasie ist der Entwurf deiner Zukunft.", kat: "Ideen & Kreativität" },
  { text: "Kombiniere Mut mit Neugier für bahnbrechende Ideen.", kat: "Ideen & Kreativität" },
  { text: "Innovation ist das Ergebnis von Beharrlichkeit und Phantasie.", kat: "Ideen & Kreativität" },
  { text: "Trau dich, anders zu denken als der Rest.", kat: "Ideen & Kreativität" },
  { text: "Der Geist ist wie ein Fallschirm – er funktioniert nur, wenn er offen ist.", kat: "Ideen & Kreativität" },
  { text: "Aus Skizzen werden Denkmäler.", kat: "Ideen & Kreativität" },
  { text: "Lass dich von der Welt inspirieren und gib ihr etwas zurück.", kat: "Ideen & Kreativität" },
  { text: "Ein Gedanke kann eine ganze Kettenreaktion auslösen.", kat: "Ideen & Kreativität" },
  { text: "Vertraue deinen Geistesblitzen.", kat: "Ideen & Kreativität" },
  { text: "Erforsche das Unbekannte mit offenem Visier.", kat: "Ideen & Kreativität" },
  { text: "Perfektion tötet Kreativität – mach einfach den ersten Entwurf.", kat: "Ideen & Kreativität" },
  { text: "Verbinde bestehende Punkte zu völlig neuen Mustern.", kat: "Ideen & Kreativität" },
  { text: "Die besten Ideen kommen beim Handeln.", kat: "Ideen & Kreativität" },
  { text: "Sei der Architekt deiner eigenen Konzepte.", kat: "Ideen & Kreativität" },
  { text: "Lass deine Vision größer sein als deine Befürchtungen.", kat: "Ideen & Kreativität" },
  { text: "Wer neue Wege gehen will, muss alte Pfade verlassen.", kat: "Ideen & Kreativität" },
  { text: "Träume sind die Blaupausen der Realität.", kat: "Ideen & Kreativität" },
  { text: "Deine einzigartige Perspektive ist dein größter Trumpf.", kat: "Ideen & Kreativität" },
  { text: "Hör auf deine Intuition – sie kennt die Abkürzung.", kat: "Ideen & Kreativität" },
  { text: "Sammle Erfahrungen wie Bausteine für deine Vision.", kat: "Ideen & Kreativität" },
  { text: "Bunte Gedanken machen die Welt lebendig.", kat: "Ideen & Kreativität" },
  { text: "Kreativität braucht keinen Erlaubnisschein.", kat: "Ideen & Kreativität" },
  { text: "Hinterfrage das Gewohnte und erschaffe das Außergewöhnliche.", kat: "Ideen & Kreativität" },
  { text: "Gestalte deine Zukunft selbst, anstatt sie zu erwarten.", kat: "Ideen & Kreativität" },
  { text: "Gedankliche Freiheit führt zu praktischer Größe.", kat: "Ideen & Kreativität" },
  { text: "Verwandle Komplexität in schlichte Eleganz.", kat: "Ideen & Kreativität" },
  { text: "Neue Pfade entstehen beim Gehen.", kat: "Ideen & Kreativität" },
  { text: "Sei neugierig wie ein Kind und entschlossen wie ein Meister.", kat: "Ideen & Kreativität" },
  { text: "Antworten findest du dort, wo du mutige Fragen stellst.", kat: "Ideen & Kreativität" },
  { text: "Nutze Kritik als Werkzeug zum Feinschliff deiner Vision.", kat: "Ideen & Kreativität" },
  { text: "Gedanken sind zollfrei – denke riesig!", kat: "Ideen & Kreativität" },
  { text: "Das Gehirn ist ein Muskel: Trainiere ihn mit neuen Ideen.", kat: "Ideen & Kreativität" },
  { text: "Erfinde Lösungen, die es gestern noch nicht gab.", kat: "Ideen & Kreativität" },
  { text: "Originalität braucht Mut zur Unvollkommenheit.", kat: "Ideen & Kreativität" },
  { text: "Denke in Möglichkeiten, nicht in Problemen.", kat: "Ideen & Kreativität" },
  { text: "Jedes Konzept beginnt mit einem einzigen Strich.", kat: "Ideen & Kreativität" },
  { text: "Lass deine Ideen die Welt bereichern.", kat: "Ideen & Kreativität" },

  // ---------------------------------------------------------
  // 151-200: FOKUS & ZIELSTREBIGKEIT
  // ---------------------------------------------------------
  { text: "Fokus schlägt Talent, wenn Talent nicht fokussiert ist.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Bleib deinem Ziel treu, auch wenn der Weg steil wird.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Konzentriere dich auf das, was du beeinflussen kannst.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Tägliche Disziplin ist die Brücke zwischen Wunsch und Realität.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Ein Ziel ohne Plan ist nur ein Wunsch – erstelle deinen Plan!", kat: "Fokus & Zielstrebigkeit" },
  { text: "Sei stärke als deine stärkste Ausrede.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Der Weg zum Erfolg ist immer im Bau – arbeite täglich daran.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Lass dich nicht von Ablenkungen vom Kurs bringen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Qualität entsteht durch Ausdauer und Präzision.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Bleib hungrig nach Fortschritt.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Vergiss das Rauschen der Welt und lausche deinen Zielen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Konsistenz schlägt Intensität auf lange Sicht.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Ein klarer Fokus bündelt Kräfte wie ein Laser.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Sag Nein zu allem, was dich deinen Zielen nicht näher bringt.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Setze Prioritäten und ziehe sie konsequent durch.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Erfolg ist das Resultat täglicher kleiner Entscheidungen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Wer zwei Hasen gleichzeitig jagt, fängt keinen von beiden.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Richte deine Aufmerksamkeit auf das Endergebnis.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Disziplin bedeutet zu tun, was getan werden muss, auch wenn man keine Lust hat.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Der Fokus bestimmt die Realität.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Halte das Ziel vor Augen und die Füße auf dem Boden.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Lass Ergebnisse für sich selbst sprechen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Kanalisiere deine Energie zielgerichtet.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Bleib stur bei deinen Zielen, aber flexibel bei deinen Methoden.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Kleine tägliche Verbesserungen summieren sich gewaltig.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Wer seinen Kurs kennt, lässt sich vom Gegenwind nicht beirren.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Fokus ist das Tor zur Höchstleistung.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Beseitige den Lärm und konzentriere dich auf die Essenz.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Präzises Handeln führt zu exakten Ergebnissen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Verliere nie die Vision aus den Augen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Lass dein Vorhaben dein einziger Maßstab sein.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Räum Hindernisse systematisch aus dem Weg.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Halte den Blick starr auf den Gipfel gerichtet.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Lass deine Disziplin lauter sein als deine Stimmung.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Kontinuität erschafft Meisterwerke.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Entscheide, was wichtig ist, und ignoriere den Rest.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Wer klare Ziele hat, braucht keine Motivation von außen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Arbeite hart in der Stille, lass deinen Erfolg den Lärm machen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Sei scharf wie eine Klinge in deiner Ausrichtung.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Gezielter Einsatz bringt maximale Wirkung.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Bleib am Ball, auch wenn die Zuschauer fehlen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Das Ziel ist nicht das Ende, sondern der Maßstab deiner Reise.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Konzentration ist die Fähigkeit, im entscheidenden Moment da zu sein.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Nutze jede Stunde als Schritt in die richtige Richtung.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Fokussiere dich auf den Prozess, die Ergebnisse folgen automatisch.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Verankere deine Ziele tief in deiner täglichen Routine.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Exzellenz ist keine Handlung, sondern eine Gewohnheit.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Setze den Meilenstein und marschiere los.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Disziplin schützt dich vor späten Reuegefühlen.", kat: "Fokus & Zielstrebigkeit" },
  { text: "Mit klarem Blick durch jede Ablenkung.", kat: "Fokus & Zielstrebigkeit" },

  // ---------------------------------------------------------
  // 201-250: DURCHHALTEVERMÖGEN & RESILIENZ
  // ---------------------------------------------------------
  { text: "Aufgeben ist keine Option, solange du noch atmest.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Stürme machen Bäume tiefer verwurzelt.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Fall siebenmal um, steh achtmal auf.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "In der Krise zeigt sich der wahre Charakter.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Aus Niederlagen werden die lehrreichsten Lektionen geboren.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Niemand hat gesagt, dass es leicht wird, aber es wird sich lohnen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Schmerz ist vorübergehend, Stolz bleibt für immer.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Harte Zeiten formen starke Menschen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Der tiefste Punkt ist die beste Basis für den Wiederaufbau.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Wer den Berg erklimmen will, muss den Aufstieg akzeptieren.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Du bist resilienter als jedes Problem vor dir.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Geduld und Spucke bringen dich weiter als Hektik.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Verwandle Steine im Weg in Stufen nach oben.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Der Weg durch die Hölle endet nur, wenn du weitergehst.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Rückschläge sind nur Anlauf für den nächsten Sprung.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Ausdauer ist der beste Freund des Erfolgs.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Wer im Nebel weitergeht, sieht als Erster die Sonne.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Glaube an dich, wenn der Sturm am lautesten brüllt.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Lass dich brechen, um stärker zusammenzuwachsen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Jede Narbe erzählt eine Geschichte von Überwindung.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Halt durch! Der schwerste Abschnitt kommt oft kurz vor der Spitze.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Aus Widrigkeiten wird Stärke geschmiedet.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Kein Regenschauer dauert ewig.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Steh deinen Mann/deine Frau, egal wie stark der Wind bläst.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Es ist immer zu früh, um aufzugeben.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Resilienz ist der Schild gegen den Zweifel.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Was dich nicht umwirft, macht dich erfahrener.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Setze deinen Weg fort, auch wenn die Beine schwer werden.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Am Ende zählt, wer noch steht.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Niederlagen sind nur Zwischenstationen auf dem Weg nach oben.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Die stärksten Diamanten entstehen unter dem höchsten Druck.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Lass dich von Rückschlägen anspornen, nicht entmutigen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Nimm den Kampf an und wachse daran.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Fehler sind der Beweis dafür, dass du es versuchst.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Bleib standhaft in deinen Werten und Plänen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Ein Schritt nach dem anderen – so durchquert man Wüsten.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Lass die Vergangenheit ruhen und kämpfe für die Zukunft.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Deine Zähigkeit entscheidet über deinen Erfolg.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Gib nicht auf kurz bevor das Wunder geschieht.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Überwindung ist der Schlüssel zur Freiheit.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Der beste Schutz gegen Misserfolg ist stetiges Weitergehen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Zeige den Problemen, wer der Chef im Haus ist.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Aus Stolpern wird Gehen, aus Gehen wird Laufen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Standfestigkeit zahlt sich immer aus.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Nichts kann dich stoppen, außer deiner eigenen Entscheidung.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Kraft wächst nicht aus Siegen, sondern aus Herausforderungen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Lerne zu ruhen, nicht aufzugeben, wenn du müde bist.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Die tiefste Nacht gebiert den hellsten Morgen.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Verwandle deine Wunden in Weisheit.", kat: "Durchhaltevermögen & Resilienz" },
  { text: "Du bist ein Kämpfer, vergiss das nie.", kat: "Durchhaltevermögen & Resilienz" },

  // ---------------------------------------------------------
  // 251-300: MINDSET & EINSTELLUNG
  // ---------------------------------------------------------
  { text: "Glaube, dass du es kannst, und du bist schon den halben Weg dort.", kat: "Mindset & Einstellung" },
  { text: "Deine Gedanken formen dein Schicksal.", kat: "Mindset & Einstellung" },
  { text: "Optimismus ist eine Entscheidung, die jeden Tag neu getroffen wird.", kat: "Mindset & Einstellung" },
  { text: "Sei dankbar für das, was ist, und mutig für das, was kommt.", kat: "Mindset & Einstellung" },
  { text: "Ein positives Mindset findet in jedem Hindernis eine Chance.", kat: "Mindset & Einstellung" },
  { text: "Erfolg ist die Einstellung, niemals aufzuhören zu lernen.", kat: "Mindset & Einstellung" },
  { text: "Dein Geist ist deine stärkste Waffe – halte ihn scharf.", kat: "Mindset & Einstellung" },
  { text: "Denke in Lösungen, nicht in Einschränkungen.", kat: "Mindset & Einstellung" },
  { text: "Selbstvertrauen entsteht durch das Überwinden von Ängsten.", kat: "Mindset & Einstellung" },
  { text: "Die Welt sieht so aus, wie du dich entscheidest sie zu sehen.", kat: "Mindset & Einstellung" },
  { text: "Befreie deinen Kopf von 'Ich kann nicht'.", kat: "Mindset & Einstellung" },
  { text: "Freue dich über Erfolge anderer und wachse selbst daran.", kat: "Mindset & Einstellung" },
  { text: "Ein starker Verstand trägt einen müden Körper.", kat: "Mindset & Einstellung" },
  { text: "Vertraue darauf, dass sich die Dinge zum Guten wenden, wenn du arbeitest.", kat: "Mindset & Einstellung" },
  { text: "Wachstum beginnt am Ende deiner Komfortzone.", kat: "Mindset & Einstellung" },
  { text: "Sei dein eigener größter Anfeuerer.", kat: "Mindset & Einstellung" },
  { text: "Mentale Stärke erfordert tägliche Hygiene deiner Gedanken.", kat: "Mindset & Einstellung" },
  { text: "Du bist das Ergebnis deiner habitualisierten Einstellungen.", kat: "Mindset & Einstellung" },
  { text: "Echte Fülle beginnt im Geist.", kat: "Mindset & Einstellung" },
  { text: "Ersetze 'Warum ich?' durch 'Versuch's doch!'.", kat: "Mindset & Einstellung" },
  { text: "Glaube an Wunder, aber verlass dich auf deine Arbeit.", kat: "Mindset & Einstellung" },
  { text: "Deine Perspektive verändert das komplette Spiel.", kat: "Mindset & Einstellung" },
  { text: "Innere Ruhe gibt äußere Kraft.", kat: "Mindset & Einstellung" },
  { text: "Sei offen für Veränderungen – sie sind der Motor des Lebens.", kat: "Mindset & Einstellung" },
  { text: "Feiere kleine Siege auf dem Weg zum großen Ziel.", kat: "Mindset & Einstellung" },
  { text: "Dein Wert hängt nicht von der Meinung anderer ab.", kat: "Mindset & Einstellung" },
  { text: "Richte deinen inneren Kompass auf Erfolg und Glück.", kat: "Mindset & Einstellung" },
  { text: "Der Verstand kreiert die Realität, in der wir leben.", kat: "Mindset & Einstellung" },
  { text: "Sei stolz auf deine Fortschritte, egal wie klein sie scheinen.", kat: "Mindset & Einstellung" },
  { text: "Positive Energie ziehst du durch positive Haltung an.", kat: "Mindset & Einstellung" },
  { text: "Lerne, das Gute in jeder Situation zu sehen.", kat: "Mindset & Einstellung" },
  { text: "Mentale Klarheit bringt physische Stärke.", kat: "Mindset & Einstellung" },
  { text: "Mach dir bewusst, wie weit du bereits gekommen bist.", kat: "Mindset & Einstellung" },
  { text: "Erfolg ist eine Geisteshaltung vor dem materiellen Resultat.", kat: "Mindset & Einstellung" },
  { text: "Nimm das Leben nicht als Last, sondern als Abenteuer.", kat: "Mindset & Einstellung" },
  { text: "Du besitzt bereits alles, was du zum Starten brauchst.", kat: "Mindset & Einstellung" },
  { text: "Lass Dankbarkeit dein täglicher Begleiter sein.", kat: "Mindset & Einstellung" },
  { text: "Nutze die Macht der positiven Glaubenssätze.", kat: "Mindset & Einstellung" },
  { text: "Der Glaube an dich selbst ist der Schlüssel zu allen Türen.", kat: "Mindset & Einstellung" },
  { text: "Transformation beginnt von innen nach außen.", kat: "Mindset & Einstellung" },
  { text: "Wer seine Gedanken kontrolliert, kontrolliert sein Leben.", kat: "Mindset & Einstellung" },
  { text: "Ein Lächeln öffnet mehr Wege als sture Gewalt.", kat: "Mindset & Einstellung" },
  { text: "Gelassenheit bringt die besten Entscheidungen hervor.", kat: "Mindset & Einstellung" },
  { text: "Denke groß, handle klug, bleibe bescheiden.", kat: "Mindset & Einstellung" },
  { text: "Deine Haltung entscheidet über deine Flughöhe.", kat: "Mindset & Einstellung" },
  { text: "Investiere in deinen Verstand, er zahlt die besten Zinsen.", kat: "Mindset & Einstellung" },
  { text: "Schüttle Zweifel ab wie Regenkleidung.", kat: "Mindset & Einstellung" },
  { text: "Nichts ist unmöglich für den, der fest daran glaubt.", kat: "Mindset & Einstellung" },
  { text: "Sei Meister deines Geistes, nicht sein Sklave.", kat: "Mindset & Einstellung" },
  { text: "Dein Potenzial wartet nur darauf, von dir abgerufen zu werden.", kat: "Mindset & Einstellung" },

  // ---------------------------------------------------------
  // 301-350: SELBSTBEWUSSTSEIN & INNERE STÄRKE
  // ---------------------------------------------------------
  { text: "Steh zu dem, wer du bist – das ist deine größte Superkraft.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Niemand kann dir das Gefühl geben, minderwertig zu sein, ohne deine Zustimmung.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist einzigartig, und genau das ist deine Stärke.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Verstelle dich nicht für andere, lebe deine eigene Wahrheit.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Selbstliebe ist das Fundament für jedes Wachstum.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du brauchst keine Erlaubnis, um großartig zu sein.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei stolz auf deine Narben, sie zeigen deinen Siegeszug.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Vertraue deinen Fähigkeiten, du hast schon vieles gemeistert.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Lass dein Licht strahlen, ohne dich zu entschuldigen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist stark genug, um jeden Sturm zu überstehen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Steh aufrecht und schau der Welt direkt in die Augen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Lass nicht zu, dass fremde Erwartungen dein Leben diktieren.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "In deiner Verletzlichkeit liegt deine wahre Stärke.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei das Original, nicht die Kopie eines anderen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist wertvoll, genau so wie du jetzt gerade bist.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Glaube an deine eigene Stimme, auch wenn sie zittert.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Gib dir selbst den Respekt, den du anderen entgegenbringst.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Deine Grenzen bestimmst ganz alleine du.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Mache dein Glück nicht von externer Bestätigung abhängig.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei mutig genug, deinen eigenen Weg zu gehen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist der Schöpfer deines eigenen Schicksals.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Steh zu deinen Fehlern, sie machen dich menschlich und stark.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Erkenne deinen eigenen Wert und fordere ihn ein.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Nimm deinen Platz in der Welt voller Stolz ein.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Lass dich nicht von Neidern verunsichern.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Innere Stärke zeigt sich in ruhiger Entschlossenheit.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei dir selbst der beste Freund und wichtigste Verbündete.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Trau deinen Entscheidungen und steh dazu.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist kein Produkt deiner Umstände, sondern deiner Entscheidungen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Vertraue deinem Bauchgefühl – es täuscht dich selten.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Achte auf deine eigenen Bedürfnisse mit der gleichen Sorge.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Selbstachtung ist unbezahlbar.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei dein eigener Fels in der Brandung.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Lass dich nicht von Zweiflern leise machen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Deine Existenz ist eine Bereicherung für die Welt.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei stolz auf deine Eigenarten – sie machen dich aus.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Nimm dir das Recht heraus, Nein zu sagen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist stärke als deine Ängste.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Lerne dich selbst kennen und du wirst unbesiegt bleiben.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Anerkennung beginnt bei dir selbst.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Steh für deine Überzeugungen ein, auch wenn du alleine stehst.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Deine innere Flamme kann von niemandem gelöscht werden.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Erlaube dir, Raum einzunehmen.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Deine Geschichte ist es wert, erzählt zu werden.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Vertraue deinem Weg, auch wenn er ungewöhnlich erscheint.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Lass deine Taten von Selbstvertrauen geprägt sein.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Gib niemals deine Integrität für schnelle Vorteile auf.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Du bist ein Unikat auf dieser Erde.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "In dir ruht eine unerschöpfliche Quelle von Mut.", kat: "Selbstbewusstsein & Innere Stärke" },
  { text: "Sei der Held deiner eigenen Geschichte.", kat: "Selbstbewusstsein & Innere Stärke" },

  // ---------------------------------------------------------
  // 351-400: ERFOLG & LEISTUNG
  // ---------------------------------------------------------
  { text: "Erfolg ist die Summe kleiner Anstrengungen, die sich täglich wiederholen.", kat: "Erfolg & Leistung" },
  { text: "Wer Höchstleistungen erbringen will, muss exzellent vorbereitet sein.", kat: "Erfolg & Leistung" },
  { text: "Erfolg kommt nicht zu dir – du musst zu ihm gehen.", kat: "Erfolg & Leistung" },
  { text: "Messe deinen Erfolg an den Hindernissen, die du überwunden hast.", kat: "Erfolg & Leistung" },
  { text: "Harte Arbeit schlägt Talent, wenn Talent nicht hart arbeitet.", kat: "Erfolg & Leistung" },
  { text: "Der Preis des Erfolgs ist Hingabe und unermüdlicher Einsatz.", kat: "Erfolg & Leistung" },
  { text: "Erfolg ist kein Zufall, sondern das Ergebnis von Strategie und Fleiß.", kat: "Erfolg & Leistung" },
  { text: "Setze dir Standards, keine Limits.", kat: "Erfolg & Leistung" },
  { text: "Spitzenleistung ist eine Frage der ständigen Vorbereitung.", kat: "Erfolg & Leistung" },
  { text: "Erfolg bedeutet, einmal mehr aufzustehen als man umgeworfen wurde.", kat: "Erfolg & Leistung" },
  { text: "Wer Großes erreichen will, muss Großen Einsatz zeigen.", kat: "Erfolg & Leistung" },
  { text: "Bringe Opfer für deine Träume, sonst werden deine Träume zum Opfer.", kat: "Erfolg & Leistung" },
  { text: "Qualität ist kein Zufall, sie ist immer das Ergebnis hoher Absichten.", kat: "Erfolg & Leistung" },
  { text: "Die Früchte des Erfolgs schmecken am besten nach hartem Kampf.", kat: "Erfolg & Leistung" },
  { text: "Erfolg erfordert Fokus, Opferbereitschaft und Ausdauer.", kat: "Erfolg & Leistung" },
  { text: "Strebe nach Exzellenz in allem, was du tust.", kat: "Erfolg & Leistung" },
  { text: "Gewinner suchen Wege, Verlierer suchen Ausreden.", kat: "Erfolg & Leistung" },
  { text: "Nutze deine Zeit produktiv, sie ist deine wertvollste Ressource.", kat: "Erfolg & Leistung" },
  { text: "Meisterschaft erfordert jahrelanges, fokussiertes Üben.", kat: "Erfolg & Leistung" },
  { text: "Erfolg ist der beste Beweis für die Richtigkeit deines Weges.", kat: "Erfolg & Leistung" },
  { text: "Lass deinen Erfolg deine lauteste Antwort sein.", kat: "Erfolg & Leistung" },
  { text: "Verdiene dir deinen Erfolg mit Schweiß und Entschlossenheit.", kat: "Erfolg & Leistung" },
  { text: "Überflügel deine eigenen Rekorde täglich.", kat: "Erfolg & Leistung" },
  { text: "Erfolg ist eine Reise, kein Zielort.", kat: "Erfolg & Leistung" },
  { text: "Lerne die Spielregeln und spiele besser als jeder andere.", kat: "Erfolg & Leistung" },
  { text: "Konkurriere nur mit deinem gestrigen Ich.", kat: "Erfolg & Leistung" },
  { text: "Wer Spitzenleistungen will, muss Spitzenaufwand betreiben.", kat: "Erfolg & Leistung" },
  { text: "Die Meile der Extra-Anstrengung ist nie überfüllt.", kat: "Erfolg & Leistung" },
  { text: "Erfolg wächst auf dem Boden von Disziplin und Haltung.", kat: "Erfolg & Leistung" },
  { text: "Setze alles auf eine Karte und arbeite hart dafür.", kat: "Erfolg & Leistung" },
  { text: "Echter Erfolg bringt andere Menschen mit nach oben.", kat: "Erfolg & Leistung" },
  { text: "Sei unermüdlich in deiner Jagd nach Fortschritt.", kat: "Erfolg & Leistung" },
  { text: "Lass dich nicht durch frühe Siege träge machen.", kat: "Erfolg & Leistung" },
  { text: "Höchstleistung entsteht unter klarem Fokus.", kat: "Erfolg & Leistung" },
  { text: "Erfolg belohnt die Fleißigen und Mutigen.", kat: "Erfolg & Leistung" },
  { text: "Wer Säen will, muss die Felder bestellen.", kat: "Erfolg & Leistung" },
  { text: "Erfolge fallen nicht vom Himmel, sie werden erarbeitet.", kat: "Erfolg & Leistung" },
  { text: "Mache Exzellenz zu deiner persönlichen Norm.", kat: "Erfolg & Leistung" },
  { text: "Der Unterschied zwischen Gut und Großartig ist die Liebe zum Detail.", kat: "Erfolg & Leistung" },
  { text: "Lass deinen Siegeswillen größer sein als die Angst zu scheitern.", kat: "Erfolg & Leistung" },
  { text: "Wer seinen Preis zahlt, wird belohnt werden.", kat: "Erfolg & Leistung" },
  { text: "Erfolg erfordert klare Entscheidungen und mutiges Handeln.", kat: "Erfolg & Leistung" },
  { text: "Baue dein Imperium Stein für Stein auf.", kat: "Erfolg & Leistung" },
  { text: "Meistere das Fundament, bevor du die Krone anstrebst.", kat: "Erfolg & Leistung" },
  { text: "Dein Erfolg inspiriert mehr Menschen als du ahnst.", kat: "Erfolg & Leistung" },
  { text: "Bleib bescheiden im Erfolg und stark im Rückschlag.", kat: "Erfolg & Leistung" },
  { text: "Mache deine Ambitionen zu Realität.", kat: "Erfolg & Leistung" },
  { text: "Leistung wird durch kontinuierliche Mühe geformt.", kat: "Erfolg & Leistung" },
  { text: "Feiere den Erfolg, aber bleibe hungrig nach mehr.", kat: "Erfolg & Leistung" },
  { text: "Erfolg ist die Belohnung für Stehvermögen.", kat: "Erfolg & Leistung" },

  // ---------------------------------------------------------
  // 401-450: MUT & DURCHBRUCH
  // ---------------------------------------------------------
  { text: "Verlasse den sicheren Hafen – Abenteuer warten auf hoher See.", kat: "Mut & Durchbruch" },
  { text: "Mut steht am Anfang des Handelns, Glück am Ende.", kat: "Mut & Durchbruch" },
  { text: "Trau dich, den ersten Schritt ins Unbekannte zu machen.", kat: "Mut & Durchbruch" },
  { text: "Breche die Ketten deiner Zweifel und fliege.", kat: "Mut & Durchbruch" },
  { text: "Das Leben beginnt dort, wo deine Angst endet.", kat: "Mut & Durchbruch" },
  { text: "Sei mutig genug, eine neue Tür zu öffnen.", kat: "Mut & Durchbruch" },
  { text: "Der Durchbruch kommt oft direkt nach dem größten Widerstand.", kat: "Mut & Durchbruch" },
  { text: "Riskiere etwas – ohne Risiko gibt es keine Belohnung.", kat: "Mut & Durchbruch" },
  { text: "Spring und das Netz wird sich weben.", kat: "Mut & Durchbruch" },
  { text: "Hör auf, auf Erlaubnis zu warten – starte einfach!", kat: "Mut & Durchbruch" },
  { text: "Mut ist der Schlüssel zu allen verschlossenen Türen.", kat: "Mut & Durchbruch" },
  { text: "Wer nicht wagt, der nicht gewinnt.", kat: "Mut & Durchbruch" },
  { text: "Die größten Entdeckungen lagen nie auf ausgetretenen Pfaden.", kat: "Mut & Durchbruch" },
  { text: "Mach den Sprung und vertraue deinen Flügeln.", kat: "Mut & Durchbruch" },
  { text: "Lass deinen Mut größer sein als deine Bequemlichkeit.", kat: "Mut & Durchbruch" },
  { text: "Herausforderungen sind Gelegenheiten für Helden.", kat: "Mut & Durchbruch" },
  { text: "Bringe das Eis zum Schmelzen durch mutiges Handeln.", kat: "Mut & Durchbruch" },
  { text: "Trau dich, deine Stimme laut zu erheben.", kat: "Mut & Durchbruch" },
  { text: "Der Durchbruch erfordert maximale Intensität im richtigen Moment.", kat: "Mut & Durchbruch" },
  { text: "Sei der Pionier deines eigenen Lebens.", kat: "Mut & Durchbruch" },
  { text: "Fürchte dich nicht vor Veränderung, umarme sie.", kat: "Mut & Durchbruch" },
  { text: "Mut wächst mit jedem Schritt, den du machst.", kat: "Mut & Durchbruch" },
  { text: "Greife nach den Gelegenheiten, wenn sie sich bieten.", kat: "Mut & Durchbruch" },
  { text: "Nimm dein Schicksal furchtlos in die Hand.", kat: "Mut & Durchbruch" },
  { text: "Sprungentscheidungen verändern oft ganze Leben.", kat: "Mut & Durchbruch" },
  { text: "Setze alles daran, Barrieren niederzureißen.", kat: "Mut & Durchbruch" },
  { text: "Beweise dir selbst, wozu du fähig bist.", kat: "Mut & Durchbruch" },
  { text: "Trau dich, deine Träume laut auszusprechen.", kat: "Mut & Durchbruch" },
  { text: "Kein Sieg ohne mutigen Einsatz.", kat: "Mut & Durchbruch" },
  { text: "Sei ein Wegbereiter, kein Mitläufer.", kat: "Mut & Durchbruch" },
  { text: "Überwinde die Hürden in deinem Geist.", kat: "Mut & Durchbruch" },
  { text: "Durchbrüche entstehen durch unnachgiebigen Druck.", kat: "Mut & Durchbruch" },
  { text: "Sei entschlossen, deine Träume wahr werden zu lassen.", kat: "Mut & Durchbruch" },
  { text: "Hab keine Angst vor großen Sprüngen – zwei kleine Abgründe überwindet man nicht.", kat: "Mut & Durchbruch" },
  { text: "Mutig zu sein heißt nicht, keine Angst zu haben, sondern es trotzdem zu tun.", kat: "Mut & Durchbruch" },
  { text: "Stürze dich ins Abenteuer des Lebens.", kat: "Mut & Durchbruch" },
  { text: "Jede große Reise beginnt mit einem mutigen Entschluss.", kat: "Mut & Durchbruch" },
  { text: "Renne auf deine Ängste zu – sie lösen sich auf.", kat: "Mut & Durchbruch" },
  { text: "Sei kühn in deiner Planung und mutig in der Umsetzung.", kat: "Mut & Durchbruch" },
  { text: "Schaffe Fakten durch mutige Entscheidungen.", kat: "Mut & Durchbruch" },
  { text: "Lass dich nicht von Sicherheit lähmen.", kat: "Mut & Durchbruch" },
  { text: "Der Durchbruch ist nur eine Entscheidung entfernt.", kat: "Mut & Durchbruch" },
  { text: "Geh dorthin, wo noch niemand war, und hinterlasse eine Spur.", kat: "Mut & Durchbruch" },
  { text: "Setze dein Segel gegen den stärksten Wind.", kat: "Mut & Durchbruch" },
  { text: "Furchtlosigkeit ist die Frucht regelmäßigen Mut-Trainings.", kat: "Mut & Durchbruch" },
  { text: "Zögere nicht lang – handle entschlossen.", kat: "Mut & Durchbruch" },
  { text: "Nimm die Herausforderung an und fordere das Schicksal heraus.", kat: "Mut & Durchbruch" },
  { text: "Dein Mut bestimmt das Ausmaß deiner Freiheit.", kat: "Mut & Durchbruch" },
  { text: "Spring über deinen eigenen Schatten.", kat: "Mut & Durchbruch" },
  { text: "Ergreife die Initiative und gestalte die Welt.", kat: "Mut & Durchbruch" },

  // ---------------------------------------------------------
  // 451-500: INSPIRATION & VISIONEN
  // ---------------------------------------------------------
  { text: "Lass deine Vision deine tägliche Motivation sein.", kat: "Inspiration & Visionen" },
  { text: "Die Welt braucht das Licht, das nur du ausstrahlen kannst.", kat: "Inspiration & Visionen" },
  { text: "Inspiriere andere durch dein Vorbild, nicht nur durch Worte.", kat: "Inspiration & Visionen" },
  { text: "Wer eine klare Vision hat, findet immer einen Weg.", kat: "Inspiration & Visionen" },
  { text: "Träume nicht dein Leben, sondern lebe deinen Traum.", kat: "Inspiration & Visionen" },
  { text: "Deine Zukunft wird durch das gestaltet, was du heute tust.", kat: "Inspiration & Visionen" },
  { text: "Sei eine Quelle der Hoffnung und der positiven Energie.", kat: "Inspiration & Visionen" },
  { text: "Blicke über den Horizont hinaus auf das, was möglich ist.", kat: "Inspiration & Visionen" },
  { text: "Große Visionen erfordern Ausdauer und Herzblut.", kat: "Inspiration & Visionen" },
  { text: "Lass dich von der Zukunft anziehen, statt von der Vergangenheit halten.", kat: "Inspiration & Visionen" },
  { text: "Deine Taten heute sind die Samen für die Ernte von morgen.", kat: "Inspiration & Visionen" },
  { text: "Schaffe etwas, das über dich hinausbesteht.", kat: "Inspiration & Visionen" },
  { text: "Ein inspirierter Geist bewegt Berge.", kat: "Inspiration & Visionen" },
  { text: "Glaube an die unendlichen Möglichkeiten des Universums.", kat: "Inspiration & Visionen" },
  { text: "Lebe so, dass dein Leben ein Kunstwerk wird.", kat: "Inspiration & Visionen" },
  { text: "Setze Zeichen, die lange nachwirken.", kat: "Inspiration & Visionen" },
  { text: "Bringe deine innere Fülle in die Welt ein.", kat: "Inspiration & Visionen" },
  { text: "Deine Vision ist der Kompass auf deiner Lebensreise.", kat: "Inspiration & Visionen" },
  { text: "Erschaffe Werte, die bleiben.", kat: "Inspiration & Visionen" },
  { text: "Gib der Welt das Beste, was du zu bieten hast.", kat: "Inspiration & Visionen" },
  { text: "Inspiration ist überall, du musst nur dein Herz öffnen.", kat: "Inspiration & Visionen" },
  { text: "Lass deine Ziele so groß sein, dass sie dich morgens aus dem Bett katapultieren.", kat: "Inspiration & Visionen" },
  { text: "Du bist ein Gestalter der Zukunft.", kat: "Inspiration & Visionen" },
  { text: "Verwurzelt in der Gegenwart, den Blick in die Zukunft gerichtet.", kat: "Inspiration & Visionen" },
  { text: "Verwandle Inspiration in greifbare Realität.", kat: "Inspiration & Visionen" },
  { text: "Sei das Vorbild, das du dir früher gewünscht hättest.", kat: "Inspiration & Visionen" },
  { text: "Visionäre lassen sich von kurzfristigen Hürden nicht ablenken.", kat: "Inspiration & Visionen" },
  { text: "Mach deinen Lebensweg zu einer inspirierenden Reise.", kat: "Inspiration & Visionen" },
  { text: "Dein Traum verdient deinen vollen Einsatz.", kat: "Inspiration & Visionen" },
  { text: "Trage Zuversicht in die Herzen anderer Menschen.", kat: "Inspiration & Visionen" },
  { text: "Wer die Sterne erreichen will, darf den Blick nicht auf den Boden richten.", kat: "Inspiration & Visionen" },
  { text: "Lass deine Vision lebendig und greifbar werden.", kat: "Inspiration & Visionen" },
  { text: "Das Leben ist zu kurz für kleine Träume.", kat: "Inspiration & Visionen" },
  { text: "Bringe deine Talente voll zur Entfaltung.", kat: "Inspiration & Visionen" },
  { text: "Lass deine Leidenschaft das Fundament deiner Vision sein.", kat: "Inspiration & Visionen" },
  { text: "Echte Inspiration führt immer zu konkretem Handeln.", kat: "Inspiration & Visionen" },
  { text: "Baue Brücken in eine bessere Zukunft.", kat: "Inspiration & Visionen" },
  { text: "Deine Vision verleiht deinem Alltag tiefen Sinn.", kat: "Inspiration & Visionen" },
  { text: "Bleib der großen Idee treu.", kat: "Inspiration & Visionen" },
  { text: "Forme die Welt nach deinen positiven Vorstellungen.", kat: "Inspiration & Visionen" },
  { text: "Jede große Veränderung begann mit einer einzelnen Vision.", kat: "Inspiration & Visionen" },
  { text: "Lass dich nicht von Bedenkenträgern bremsen.", kat: "Inspiration & Visionen" },
  { text: "Inspiriere deine Umwelt durch exzellente Ergebnisse.", kat: "Inspiration & Visionen" },
  { text: "Geh deinen Weg voller Anmut und Stärke.", kat: "Inspiration & Visionen" },
  { text: "Dein Beitrag zählt – unterschätze ihn niemals.", kat: "Inspiration & Visionen" },
  { text: "Blicke mit Vorfreude auf das, was du noch erschaffen wirst.", kat: "Inspiration & Visionen" },
  { text: "Du bist der Schöpfer deiner nächsten großen Etappe.", kat: "Inspiration & Visionen" },
  { text: "Entfache das Feuer in dir und leuchte hell.", kat: "Inspiration & Visionen" },
  { text: "Vision plus Aktion ergibt unaufhaltsame Transformation.", kat: "Inspiration & Visionen" },
  { text: "Dein Weg ist das Ziel – genieße jeden Schritt voller Motivation!", kat: "Inspiration & Visionen" },

  // ---------------------------------------------------------
  // 501-550: GAMING & TECH-HUMOR
  // ---------------------------------------------------------
  { text: "Ein Bug ist auch nur eine undokumentierte Idee.", kat: "Gaming & Tech-Humor" },
  { text: "Gönn dir ein Level-Up für deinen Verstand.", kat: "Gaming & Tech-Humor" },
  { text: "Kaffee verwandelt Code in Realität.", kat: "Gaming & Tech-Humor" },
  { text: "Das echte Leben hat die beste Grafik, aber keinen Reset-Button.", kat: "Gaming & Tech-Humor" },
  { text: "Erstmal abspeichern, bevor das nächste Abenteuer startet.", kat: "Gaming & Tech-Humor" },
  { text: "Wenn der Code auf Anhieb funktioniert, sei misstrauisch.", kat: "Gaming & Tech-Humor" },
  { text: "Egal wie schwer das Level ist, es gibt immer ein Pattern.", kat: "Gaming & Tech-Humor" },
  { text: "Lieber einmal zu viel gespeichert als alles neu gebaut.", kat: "Gaming & Tech-Humor" },
  { text: "Du bist nicht langsam, du lädst nur gerade die besten Ideen.", kat: "Gaming & Tech-Humor" },
  { text: "Ctrl + Z löscht Fehler, Mut erschafft Neues.", kat: "Gaming & Tech-Humor" },
  { text: "Gamer geben nicht auf – sie respawnen.", kat: "Gaming & Tech-Humor" },
  { text: "Ein gut geplantes Skript spart zehn Stunden Fehlersuche.", kat: "Gaming & Tech-Humor" },
  { text: "Nutze Shortcuts für die Arbeit, nicht fürs Leben.", kat: "Gaming & Tech-Humor" },
  { text: "Dein Mindset braucht ab und zu ein Firmware-Update.", kat: "Gaming & Tech-Humor" },
  { text: "Es gibt 10 Arten von Menschen: Die, die Binärcode verstehen, und die, die es nicht tun.", kat: "Gaming & Tech-Humor" },
  { text: "Manchmal hilft nur: Einmal den Kopf neu starten.", kat: "Gaming & Tech-Humor" },
  { text: "Sammle Erfahrungspunkte in jedem Projekt.", kat: "Gaming & Tech-Humor" },
  { text: "Der beste Ping bringt nichts ohne klare Zielausrichtung.", kat: "Gaming & Tech-Humor" },
  { text: "Der schwerste Endboss ist dein eigener Schweinehund.", kat: "Gaming & Tech-Humor" },
  { text: "Programmieren ist die Kunst, Steinen das Denken beizubringen.", kat: "Gaming & Tech-Humor" },
  { text: "Suche nicht nach Glitches im Leben, erschaffe deine eigenen Regeln.", kat: "Gaming & Tech-Humor" },
  { text: "Selbst die stärkste GPU braucht ein gutes Kühlungssystem.", kat: "Gaming & Tech-Humor" },
  { text: "Sei der Admin in deiner eigenen Welt.", kat: "Gaming & Tech-Humor" },
  { text: "Ein wahrer Profi kennt die Tastenkombination zum Erfolg.", kat: "Gaming & Tech-Humor" },
  { text: "Nicht jeder Bug muss gefixt werden, manch einer wird zum Kult.", kat: "Gaming & Tech-Humor" },
  { text: "Fortschritt wird in gecrafteten Blöcken gemessen.", kat: "Gaming & Tech-Humor" },
  { text: "Bau deine Träume Stein für Stein – wie in Minecraft.", kat: "Gaming & Tech-Humor" },
  { text: "Das Leben läuft flüssiger mit 144 Hz Positivität.", kat: "Gaming & Tech-Humor" },
  { text: "Mach kein Alt+F4 auf deine Pläne, wenn es knifflig wird.", kat: "Gaming & Tech-Humor" },
  { text: "Entwickler schlafen nicht, sie rendern Lösungen.", kat: "Gaming & Tech-Humor" },
  { text: "Du hast das Zeug zum Speedrun, aber genieße die Story.", kat: "Gaming & Tech-Humor" },
  { text: "Lerne die Spielmechanik, dann meistere das Spiel.", kat: "Gaming & Tech-Humor" },
  { text: "Hardware ist der Körper, Mindset ist das Betriebssystem.", kat: "Gaming & Tech-Humor" },
  { text: "Sei kein NPC in deinem eigenen Projekt.", kat: "Gaming & Tech-Humor" },
  { text: "Highscores werden nicht im Ruhezustand aufgestellt.", kat: "Gaming & Tech-Humor" },
  { text: "Gute Ideen sind wie Easter Eggs: Man muss genau hinschauen.", kat: "Gaming & Tech-Humor" },
  { text: "Kommentiere deine Schritte, damit dein zukünftiges Ich durchblickt.", kat: "Gaming & Tech-Humor" },
  { text: "Kein System ist absolut fehlerfrei – bleib anpassungsfähig.", kat: "Gaming & Tech-Humor" },
  { text: "Sammle Ressourcen, bevor du das riesige Bauwerk beginnst.", kat: "Gaming & Tech-Humor" },
  { text: "Die besten Abenteuer beginnen jenseits der Map-Grenzen.", kat: "Gaming & Tech-Humor" },
  { text: "Lag gehört zum Leben – bleib geduldig.", kat: "Gaming & Tech-Humor" },
  { text: "Jede Zeile Code bringt dich dem Ziel ein Stück näher.", kat: "Gaming & Tech-Humor" },
  { text: "Drücke F für alle Pläne, die nicht funktioniert haben, und mach weiter.", kat: "Gaming & Tech-Humor" },
  { text: "Dein Skillset wächst mit jeder gelösten Quest.", kat: "Gaming & Tech-Humor" },
  { text: "Halte deinen Arbeitsspeicher frei von negativem Ballast.", kat: "Gaming & Tech-Humor" },
  { text: "Sidequests machen das Hauptspiel erst richtig spannend.", kat: "Gaming & Tech-Humor" },
  { text: "Ein gutes Layout ist wie eine aufgeräumte Hotbar.", kat: "Gaming & Tech-Humor" },
  { text: "Ladezeit ist Bedenkzeit.", kat: "Gaming & Tech-Humor" },
  { text: "Validiere deine Inputs, bevor du Schlüsse ziehst.", kat: "Gaming & Tech-Humor" },
  { text: "Du bist der Developer deiner eigenen Zukunft.", kat: "Gaming & Tech-Humor" },

  // ---------------------------------------------------------
  // 551-600: ACHTSAMKEIT & PAUSEN
  // ---------------------------------------------------------
  { text: "Auch der schnellste Prozessor braucht mal eine Abkühlung.", kat: "Achtsamkeit & Pausen" },
  { text: "Pause machen ist kein Aufgeben, sondern Auftanken.", kat: "Achtsamkeit & Pausen" },
  { text: "Atme tief durch – die Welt dreht sich auch kurz ohne dein Zutun weiter.", kat: "Achtsamkeit & Pausen" },
  { text: "Eine Pause ist kein Zeitverlust, sondern eine Investition.", kat: "Achtsamkeit & Pausen" },
  { text: "Gönn deinen Gedanken eine Ruhephase für frische Blickwinkel.", kat: "Achtsamkeit & Pausen" },
  { text: "Wer immer nur rennt, übersieht die schönsten Orte am Wegesrand.", kat: "Achtsamkeit & Pausen" },
  { text: "Schalte kurz ab, um danach wieder klarer zu sehen.", kat: "Achtsamkeit & Pausen" },
  { text: "In der Stille entstehen oft die lautesten Geistesblitze.", kat: "Achtsamkeit & Pausen" },
  { text: "Achtsamkeit ist die Kunst, den jetzigen Moment zu schätzen.", kat: "Achtsamkeit & Pausen" },
  { text: "Halte inne und spüre, wie weit du schon gekommen bist.", kat: "Achtsamkeit & Pausen" },
  { text: "Qualität braucht Zeit – und Zeit braucht Pausen.", kat: "Achtsamkeit & Pausen" },
  { text: "Räume deinen Kopf so regelmäßig auf wie deinen Schreibtisch.", kat: "Achtsamkeit & Pausen" },
  { text: "Der Akku muss geladen werden, bevor er Leistung bringen kann.", kat: "Achtsamkeit & Pausen" },
  { text: "Ein ruhiger Geist trifft die besten Entscheidungen.", kat: "Achtsamkeit & Pausen" },
  { text: "Gönne dir den Luxus, kurz einfach gar nichts zu tun.", kat: "Achtsamkeit & Pausen" },
  { text: "Entschleunigung bringt oft die schnellsten Durchbrüche.", kat: "Achtsamkeit & Pausen" },
  { text: "Horche nach innen, bevor du nach außen handelst.", kat: "Achtsamkeit & Pausen" },
  { text: "Vergiss im Eifer des Gefechts das Durchatmen nicht.", kat: "Achtsamkeit & Pausen" },
  { text: "Der Weg ist lang, schone deine Kräfte vorausschauend.", kat: "Achtsamkeit & Pausen" },
  { text: "Nimm dir Zeit für die Dinge, die dich von innen heraus erfreuen.", kat: "Achtsamkeit & Pausen" },
  { text: "Ausruhen ist eine Form von Selbstachtung.", kat: "Achtsamkeit & Pausen" },
  { text: "Manchmal ist Nichts-Tun die produktivste Handlung.", kat: "Achtsamkeit & Pausen" },
  { text: "Lass den Druck los und spüre die Leichtigkeit.", kat: "Achtsamkeit & Pausen" },
  { text: "Schärfe die Säge, bevor du den nächsten Baum fällst.", kat: "Achtsamkeit & Pausen" },
  { text: "Ein Spaziergang bringt Gedanken ins Rollen.", kat: "Achtsamkeit & Pausen" },
  { text: "In der Ruhe liegt die wahre Schaffenskraft.", kat: "Achtsamkeit & Pausen" },
  { text: "Mach mal kurz das Fenster auf und lass frische Luft herein.", kat: "Achtsamkeit & Pausen" },
  { text: "Achtsamkeit verwandelt Alltägliches in etwas Besonderes.", kat: "Achtsamkeit & Pausen" },
  { text: "Schütze deine Energie wie deinen wertvollsten Schatz.", kat: "Achtsamkeit & Pausen" },
  { text: "Lass das Multitasking sein und sei ganz im Hier und Jetzt.", kat: "Achtsamkeit & Pausen" },
  { text: "Der Kopf braucht Pause, damit das Herz nachkommen kann.", kat: "Achtsamkeit & Pausen" },
  { text: "Hektik erzeugt Fehler, Ruhe erschafft Meisterwerke.", kat: "Achtsamkeit & Pausen" },
  { text: "Gib dir selbst die Erlaubnis durchzuatmen.", kat: "Achtsamkeit & Pausen" },
  { text: "Trinke ein Glas Wasser und entspanne deine Schultern.", kat: "Achtsamkeit & Pausen" },
  { text: "Dein Wert misst sich nicht an deiner ständigen Erreichbarkeit.", kat: "Achtsamkeit & Pausen" },
  { text: "Kleine Auszeiten verhindern große Erschöpfungen.", kat: "Achtsamkeit & Pausen" },
  { text: "Betrachte deine Gedanken wie Wolken am Himmel – lass sie ziehen.", kat: "Achtsamkeit & Pausen" },
  { text: "Finde deinen eigenen Rhythmus statt dem der anderen zu folgen.", kat: "Achtsamkeit & Pausen" },
  { text: "Kreativität erfordert einen freien Kopffreiraum.", kat: "Achtsamkeit & Pausen" },
  { text: "Setze den Fokus neu, indem du kurz den Blick abschweifen lässt.", kat: "Achtsamkeit & Pausen" },
  { text: "Erholung ist der Grundstein für nachhaltigen Erfolg.", kat: "Achtsamkeit & Pausen" },
  { text: "Nimm dir Zeit, die kleinen Erfolge bewusst wahrzunehmen.", kat: "Achtsamkeit & Pausen" },
  { text: "Sei achtsam mit deinen Gedanken – sie werden deine Realität.", kat: "Achtsamkeit & Pausen" },
  { text: "Manchmal ist Abstand halten der einzige Weg zu verstehen.", kat: "Achtsamkeit & Pausen" },
  { text: "Lass den Arbeitstag in Ruhe ausklingen.", kat: "Achtsamkeit & Pausen" },
  { text: "Stille ist kein Mangel an Geräuschen, sondern Anwesenheit von Frieden.", kat: "Achtsamkeit & Pausen" },
  { text: "Bleibe gelassen, wenn der Sturm draußen tobt.", kat: "Achtsamkeit & Pausen" },
  { text: "Körper und Geist arbeiten als Team – pflege beide.", kat: "Achtsamkeit & Pausen" },
  { text: "Der beste Moment zur Entspannung ist, wenn man keine Zeit dafür hat.", kat: "Achtsamkeit & Pausen" },
  { text: "Lebe im Moment, denn er ist einzigartig.", kat: "Achtsamkeit & Pausen" },

  // ---------------------------------------------------------
  // 601-650: COMMUNITY & TEAMWORK
  // ---------------------------------------------------------
  { text: "Zusammen baut man die stabilsten Brücken.", kat: "Community & Teamwork" },
  { text: "Ein Einzelner ist ein Gedanke, eine Community ist eine Bewegung.", kat: "Community & Teamwork" },
  { text: "Gemeinsam wird aus vielen kleinen Funken ein großes Feuer.", kat: "Community & Teamwork" },
  { text: "Gute Teams teilen nicht nur Arbeit, sondern verdoppeln die Freude.", kat: "Community & Teamwork" },
  { text: "Alleine ist man schnell, zusammen kommt man weitaus weiter.", kat: "Community & Teamwork" },
  { text: "Der Austausch von Ideen bringt das größte Wachstum.", kat: "Community & Teamwork" },
  { text: "In einer starken Community findet jeder seinen passenden Platz.", kat: "Community & Teamwork" },
  { text: "Mache das Wissen anderer zu deinem Gewinn und teile deines.", kat: "Community & Teamwork" },
  { text: "Zusammenarbeit verwandelt Träume in handfeste Realität.", kat: "Community & Teamwork" },
  { text: "Respekt und Zuverlässigkeit bilden das Fundament jedes Teams.", kat: "Community & Teamwork" },
  { text: "Zusammen sind wir unschlagbar vielseitig.", kat: "Community & Teamwork" },
  { text: "Echtes Teamwork zeigt sich, wenn es mal schwierig wird.", kat: "Community & Teamwork" },
  { text: "Inspiriere deine Mitmenschen und lass dich von ihnen tragen.", kat: "Community & Teamwork" },
  { text: "Gemeinsamer Erfolg schmeckt um Längen besser.", kat: "Community & Teamwork" },
  { text: "Vielfalt in Meinungen erzeugt das beste Endergebnis.", kat: "Community & Teamwork" },
  { text: "Halte anderen die Tür offen – jemand wird sie für dich aufhalten.", kat: "Community & Teamwork" },
  { text: "Ein starkes Netzwerk stärkt den Rücken in schweren Zeiten.", kat: "Community & Teamwork" },
  { text: "Zusammen erschaffen wir Welten, die alleine undenkbar wären.", kat: "Community & Teamwork" },
  { text: "Der beste Weg zu lernen ist, anderen beim Wachsen zu helfen.", kat: "Community & Teamwork" },
  { text: "Synergie bedeutet: Das Ganze ist mehr als die Summe seiner Teile.", kat: "Community & Teamwork" },
  { text: "Gute Kommunikation löst Probleme, bevor sie entstehen.", kat: "Community & Teamwork" },
  { text: "Unterstützung anzunehmen ist ein Zeichen von Stärke.", kat: "Community & Teamwork" },
  { text: "Community ist da, wo man gemeinsam an Visionen baut.", kat: "Community & Teamwork" },
  { text: "Gemeinsame Meilensteine verbinden für die Ewigkeit.", kat: "Community & Teamwork" },
  { text: "Teile deinen Fortschritt und ziehe andere mit nach oben.", kat: "Community & Teamwork" },
  { text: "Zusammen finden wir Lösungen, wo der Einzelne nur Wände sieht.", kat: "Community & Teamwork" },
  { text: "Wertschätzung ist der Treibstoff für gutes Teamwork.", kat: "Community & Teamwork" },
  { text: "Lass uns gemeinsam die Standards von morgen setzen.", kat: "Community & Teamwork" },
  { text: "Eine helfende Hand zur rechten Zeit verändert alles.", kat: "Community & Teamwork" },
  { text: "Kein Meister fällt vom Himmel, aber im Team lernt man schneller.", kat: "Community & Teamwork" },
  { text: "Gemeinsames Lachen schweißt fester zusammen als jede Regel.", kat: "Community & Teamwork" },
  { text: "Lass uns Wissen teilen statt Geheimnisse zu hüllen.", kat: "Community & Teamwork" },
  { text: "Die Stärke des Teams liegt in jedem einzelnen Mitglied.", kat: "Community & Teamwork" },
  { text: "Mache die Ziele der Gemeinschaft zu deinem persönlichen Ansporn.", kat: "Community & Teamwork" },
  { text: "Verbindung entsteht durch ehrliches Interesse am anderen.", kat: "Community & Teamwork" },
  { text: "Zusammen gestalten wir den Wandel.", kat: "Community & Teamwork" },
  { text: "Ein aufmunterndes Wort kann ein ganzes Projekt retten.", kat: "Community & Teamwork" },
  { text: "Open Source Mindset: Teilen bringt alle voran.", kat: "Community & Teamwork" },
  { text: "Wir ziehen alle am selben Strang – vorwärts!", kat: "Community & Teamwork" },
  { text: "Gegenseitiges Vertrauen macht Unmögliches möglich.", kat: "Community & Teamwork" },
  { text: "Bau Brücken statt Mauern zu deinen Mitgestaltern.", kat: "Community & Teamwork" },
  { text: "Gemeinsam wachsen macht doppelt so viel Freude.", kat: "Community & Teamwork" },
  { text: "Jede Perspektive bringt ein neues Puzzleteil ein.", kat: "Community & Teamwork" },
  { text: "Zusammen erreichen wir neue Höhen.", kat: "Community & Teamwork" },
  { text: "Ein gutes Team ergänzt sich in seinen Schwächen.", kat: "Community & Teamwork" },
  { text: "Echte Community zeigt sich im täglichen Miteinander.", kat: "Community & Teamwork" },
  { text: "Treibe gemeinsame Projekte mit Leidenschaft voran.", kat: "Community & Teamwork" },
  { text: "Sei der Funke, der andere zum Strahlen bringt.", kat: "Community & Teamwork" },
  { text: "Gemeinsam erschaffen wir bleibende Werte.", kat: "Community & Teamwork" },
  { text: "Einer für alle, alle für die Idee!", kat: "Community & Teamwork" },

  // ---------------------------------------------------------
  // 651-700: FEHLERKULTUR & EXPERIMENTIEREN
  // ---------------------------------------------------------
  { text: "Der erste Entwurf muss nicht perfekt sein, er muss nur existieren.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Aus Fehlern entstehen oft die besten Erfindungen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Wer nie scheitert, hat sich nie weit genug herausgewagt.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Ein Prototyp lehrt dich mehr als tausend Theorien.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Sieh Fehler nicht als Niederlage, sondern als kostenlose Lektion.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Probieren geht über Studieren – fang einfach an!", kat: "Fehlerkultur & Experimentieren" },
  { text: "Perfektionismus ist der größte Feind des Fortschritts.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Mut bedeutet, auch mal eine falsche Abzweigung zu testen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Jeder Irrtum bringt dich der richtigen Lösung einen Schritt näher.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Experimentiere wild, lerne schnell, passe dich an.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Fehler sind die Wegweiser auf der Straße zur Innovation.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Schlechte Skizzen sind besser als perfekte Gedanken im Kopf.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Sei mutig genug, etwas Schlechtes zu erschaffen, um es gut zu machen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Aus Schrott wird manchmal Gold – hab Geduld mit Experimenten.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Lache über deine Pannen und baue sie ins Design ein.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Hinterfrage den Standard und teste das Unerwartete.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Wer Angst vor Fehlern hat, bremst sein eigenes Talent.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Ein gescheiterter Versuch ist kein verschwendeter Tag.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Testen, anpassen, wiederholen – das ist der Weg.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Trau dich, unkonventionelle Lösungsansätze auszuprobieren.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Aus Chaos entsteht die neue Ordnung.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Mach Fehler früh, damit du früher erfolgreich bist.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Kein Meisterwerk entstand ohne unzählige Korrekturen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Lass dich von Rückschlägen neugierig machen, nicht frustrieren.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Experimente sind die Spielwiese deines Verstandes.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Nimm das Scheitern als Feedback, nicht als Urteil.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Verändere Variablen, bis das Ergebnis stimmt.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Trau dich, den gewohnten Pfad zu verlassen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Ein Stolperstein ist nur eine Stufe zum nächsten Level.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Suche nicht nach Schuldigen, sondern nach besseren Wegen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Jedes Experiment erweitert deinen Horizont.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Mach den ersten unperfekten Schritt noch heute.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Kreativität braucht den Freiraum, Unsinn machen zu dürfen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Das schönste Feedback ist ein behobenes Problem.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Fehler zeigen dir genau, wo noch Potenzial schlummert.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Mache deine Experimente sichtbar für die Welt.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Sei ein Wissenschaftler deines eigenen Lebens.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Unvollkommenheit ist der Anfang jeder Weiterentwicklung.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Wer nichts wagt, erfährt nie, was möglich gewesen wäre.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Fehler machen dich menschlich und authentisch.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Der Weg zur Perfektion führt mitten durch das Chaos.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Halte dich nicht lange mit Bedauern auf – korrigiere und weiter!", kat: "Fehlerkultur & Experimentieren" },
  { text: "Erlaube dir, ein Lernender zu sein.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Gute Ideen reifen an den Hürden, die sie überwinden.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Ein falscher Schritt ist immer noch Bewegung.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Das größte Risiko ist es, gar kein Risiko einzugehen.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Der Radiergummi ist genauso wichtig wie der Bleistift.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Lerne, Rückschläge mit einem Lächeln zu quittieren.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Sei offen für unerwartete Resultate deiner Arbeit.", kat: "Fehlerkultur & Experimentieren" },
  { text: "Fortschritt ist ein Prozess aus Versuch und Anpassung.", kat: "Fehlerkultur & Experimentieren" }
];

// 2. Die Funktion zum Ziehen und Ersetzen im HTML
function zeigeSpruch() {
  const randomIndex = Math.floor(Math.random() * sprueche.length);
  const spruch = sprueche[randomIndex];

  // Schreibt den Text direkt in das HTML-Element mit der ID "spruch-anzeige"
  document.getElementById("spruch-anzeige").innerText = spruch.text;
}