const sprueche = [
  // 1-50: Neuanfang & Aktion
  "Jeder Tag ist eine neue Chance, deine Geschichte neu zu schreiben.",
  "Dein einziger Limit bist du selbst – spreng die Grenzen!",
  "Der beste Zeitpunkt anzufangen war gestern. Der zweitbeste ist JETZT.",
  "Kleine Schritte jeden Tag führen zu riesigen Erfolgen.",
  "Vergleiche dich nur mit der Person, die du gestern warst.",
  "Aus Mut gemacht: Wer riskiert, kann gewinnen.",
  "Steh auf, richte deine Krone und geh weiter.",
  "Dein Potenzial ist unendlich – hör auf, dich klein zu machen.",
  "Erfolg beginnt im Kopf, Durchhaltevermögen im Herzen.",
  "Heute ist der Tag, an dem du deiner Zukunft danken wirst.",
  "Warte nicht auf den perfekten Moment, nimm den Moment und mach ihn perfekt.",
  "Starte dort, wo du stehst. Nutze, was du hast. Tue, was du kannst.",
  "Zweifel töten mehr Träume als Versagen es jemals könnte.",
  "Mach heute etwas, worauf du morgen stolz sein kannst.",
  "Der erste Schritt ist immer der schwerste, aber er führt ans Ziel.",
  "Wer keine Fehler macht, macht wahrscheinlich gar nichts.",
  "Verwandle deine Wünsche in konkrete Ziele.",
  "Du musst nicht großartig starten, aber du musst starten, um großartig zu werden.",
  "Heute ist ein großartiger Tag für einen Neuanfang.",
  "Setze dir Tore und laufe, bis du sie erreichst.",
  "Ein Jahr von heute an wirst du dir wünschen, du hättest heute angefangen.",
  "Aktion besiegt Angst.",
  "Lass deine Taten lauter sprechen als deine Worte.",
  "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.",
  "Es gibt keinen Aufzug zum Erfolg – du musst die Treppe nehmen.",
  "Jedes Hindernis ist ein Wegweiser in Richtung Wachstum.",
  "Breche den alten Trotzt auf und mach Raum für Neues.",
  "Aus Ausreden werden niemals Ergebnisse.",
  "Sei die Veränderung, die du in deiner Welt sehen willst.",
  "Mut bedeutet nicht die Abwesenheit von Angst, sondern das Handeln trotz ihr.",
  "Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.",
  "Du bist der Regisseur deines eigenen Lebens.",
  "Geh den Extra-Kilometer, dort ist es nie überfüllt.",
  "Taten erschaffen Fakten.",
  "Der Unterschied zwischen Träumen und Erreichen ist Disziplin.",
  "Beginne den Tag mit einer klaren Absicht.",
  "Verlasse deine Komfortzone – dort geschieht die Magie.",
  "Mach deinen Erfolg unumgänglich.",
  "Heute investierst du in die Person, die du morgen bist.",
  "Setze dein Fundament Stein für Stein.",
  "Die Beste Zeit für Veränderungen ist genau in diesem Augenblick.",
  "Richte deinen Blick nach vorne und geh los.",
  "Hör auf zu träumen, fang an zu bauen.",
  "Aus Versuchen entstehen Möglichkeiten.",
  "Glaube an den Prozess, auch wenn das Ziel noch fern scheint.",
  "Ein Funke Tatenkraft wiegt mehr als ein Ozean voller Absichten.",
  "Greif nach den Sternen, selbst wenn du stolperst, landest du oben.",
  "Lass dich nicht vom Tempo anderer verunsichern.",
  "Entscheide dich täglich neu für deine Träume.",
  "Dein Wille bestimmt deine Richtung.",

  // 51-100: Energie & Power
  "Lass deine Energie sprechen, bevor du ein Wort sagst.",
  "Vollgas voraus! Es gibt keine Hindernisse, nur Herausforderungen.",
  "Brenne für deine Träume, bis sie Realität werden.",
  "Deine Energie zieht deine Zukunft an – halte sie hoch!",
  "Nicht warten, bis der Sturm vorbeizieht – lerne im Regen zu tanzen.",
  "Energie folgt dem Fokus: Richte deinen Blick auf das Ziel.",
  "Lade deine Akkus mit positiven Gedanken und leg los.",
  "Du bist ein Kraftwerk voller Ideen und Tatendrang.",
  "Mach deine Zweifel stumm und deine Taten laut.",
  "Kein Hindernis ist zu hoch, wenn dein Wille stark genug ist.",
  "Lass dich von deiner Leidenschaft antreiben.",
  "Spüre die Kraft, die in jedem neuen Moment steckt.",
  "Stecke alle mit deiner Begeisterung an.",
  "Gib jedem Tag die Chance, dein persönlich bester zu werden.",
  "Volle Kraft voraus auf deine Ziele zu.",
  "Power entsteht aus der Entscheidung, niemals aufzugeben.",
  "Transformiere Stress in reine Handlungsenergie.",
  "Sei ein Magnet für positive Ergebnisse.",
  "Energie lässt sich nicht stoppen, nur lenken.",
  "Mit der richtigen Einstellung gibt es keine Grenzen.",
  "Nimm dir den Raum, den du brauchst, um zu strahlen.",
  "Deine Schwingung bestimmt deine Ausstrahlung.",
  "Fülle deinen Geist mit Zuversicht.",
  "In dir steckt mehr Kraft, als du dir vorstellst.",
  "Aktiviere deine innere Stärke und marschiere los.",
  "Wer brennt, muss keine Angst vor der Kälte haben.",
  "Schüttel den Staub ab und starte durch.",
  "Mach deine Energie zu deiner Visitenkarte.",
  "Lass dich von Barrieren nicht bremsen, sondern katapultieren.",
  "Adrenalin und Fokus bilden dein bestes Werkzeug.",
  "Du bist der Kapitän deines Schiffs – nimm das Steuer fest in die Hand.",
  "Lebe mit Intensität und Hingabe.",
  "Gedanken kreieren Realität – denke stark!",
  "Fokus auf das Positivste bringt die meiste Kraft.",
  "Setze neue Standards für dein Energieniveau.",
  "Sei unaufhaltsam in deinem Streben.",
  "Bring deine Ideen mit voller Wucht auf die Straße.",
  "Dynamik entsteht durch stetige Bewegung.",
  "Tanke Zuversicht und starte die Motoren.",
  "Aus Begeisterung wächst unerschöpfliche Ausdauer.",
  "Die eigene Überzeugung ist der stärkste Treibstoff.",
  "Bleib unter Strom und setze Zeichen.",
  "Jeder Puls ist eine Erinnerung an dein Potenzial.",
  "Deine Leidenschaft ist dein persönlicher Turbolader.",
  "Schaffe Ergebnisse, die deine kühnsten Erwartungen übertreffen.",
  "Lass den inneren Funken zum Flächenbrand werden.",
  "Power ist keine Frage des Glücks, sondern der Haltung.",
  "Leuchte so hell, dass Zweifel im Schatten verschwinden.",
  "Überwinde den Trägheitsmoment – danach wird alles leichter.",
  "Deine Energie zeigt den Weg.",

  // 101-150: Ideen & Kreativität
  "Große Ideen beginnen oft mit einem mutigen Gedanken.",
  "Denke nicht outside the box – denk so, als gäbe es gar keine Box.",
  "Jeder Experte war einmal ein Anfänger. Trau dich!",
  "Kreativität ist Intelligenz, die Spaß hat.",
  "Probieren geht über Studieren: Mach deine Idee sichtbar.",
  "Aus Fehlern entstehen oft die besten Erfindungen.",
  "Hab keine Angst vor verrückten Ideen – sie verändern die Welt.",
  "Schreib deine Visionen auf und erwecke sie zum Leben.",
  "Erfinde dich täglich neu und bleibe neugierig.",
  "Verwandle Herausforderungen in deine nächsten Meisterwerke.",
  "Ein unbeschriebenes Blatt ist die Leinwand deiner Möglichkeiten.",
  "Kreative Köpfe suchen Lösungen, wo andere Grenzen sehen.",
  "Inspiration findet dich beim Arbeiten, nicht beim Warten.",
  "Deine Fantasie ist der Entwurf deiner Zukunft.",
  "Kombiniere Mut mit Neugier für bahnbrechende Ideen.",
  "Innovation ist das Ergebnis von Beharrlichkeit und Phantasie.",
  "Trau dich, anders zu denken als der Rest.",
  "Der Geist ist wie ein Fallschirm – er funktioniert nur, wenn er offen ist.",
  "Aus Skizzen werden Denkmäler.",
  "Lass dich von der Welt inspirieren und gib ihr etwas zurück.",
  "Ein Gedanke kann eine ganze Kettenreaktion auslösen.",
  "Vertraue deinen Geistesblitzen.",
  "Erforsche das Unbekannte mit offenem Visier.",
  "Perfektion tötet Kreativität – mach einfach den ersten Entwurf.",
  "Verbinde bestehende Punkte zu völlig neuen Mustern.",
  "Die besten Ideen kommen beim Handeln.",
  "Sei der Architekt deiner eigenen Konzepte.",
  "Lass deine Vision größer sein als deine Befürchtungen.",
  "Wer neue Wege gehen will, muss alte Pfade verlassen.",
  "Träume sind die Blaupausen der Realität.",
  "Deine einzigartige Perspektive ist dein größter Trumpf.",
  "Hör auf deine Intuition – sie kennt die Abkürzung.",
  "Sammle Erfahrungen wie Bausteine für deine Vision.",
  "Bunte Gedanken machen die Welt lebendig.",
  "Kreativität braucht keinen Erlaubnisschein.",
  "Hinterfrage das Gewohnte und erschaffe das Außergewöhnliche.",
  "Gestalte deine Zukunft selbst, anstatt sie zu erwarten.",
  "Gedankliche Freiheit führt zu praktischer Größe.",
  "Verwandle Komplexität in schlichte Eleganz.",
  "Neue Pfade entstehen beim Gehen.",
  "Sei neugierig wie ein Kind und entschlossen wie ein Meister.",
  "Antworten findest du dort, wo du mutige Fragen stellst.",
  "Nutze Kritik als Werkzeug zum Feinschliff deiner Vision.",
  "Gedanken sind zollfrei – denke riesig!",
  "Das Gehirn ist ein Muskel: Trainiere ihn mit neuen Ideen.",
  "Erfinde Lösungen, die es gestern noch nicht gab.",
  "Originalität braucht Mut zur Unvollkommenheit.",
  "Denke in Möglichkeiten, nicht in Problemen.",
  "Jedes Konzept beginnt mit einem einzigen Strich.",
  "Lass deine Ideen die Welt bereichern.",

  // 151-200: Fokus & Zielstrebigkeit
  "Fokus schlägt Talent, wenn Talent nicht fokussiert ist.",
  "Bleib deinem Ziel treu, auch wenn der Weg steil wird.",
  "Konzentriere dich auf das, was du beeinflussen kannst.",
  "Tägliche Disziplin ist die Brücke zwischen Wunsch und Realität.",
  "Ein Ziel ohne Plan ist nur ein Wunsch – erstelle deinen Plan!",
  "Sei stärker als deine stärkste Ausrede.",
  "Der Weg zum Erfolg ist immer im Bau – arbeite täglich daran.",
  "Lass dich nicht von Ablenkungen vom Kurs bringen.",
  "Qualität entsteht durch Ausdauer und Präzision.",
  "Bleib hungrig nach Fortschritt.",
  "Vergiss das Rauschen der Welt und lausche deinen Zielen.",
  "Konsistenz schlägt Intensität auf lange Sicht.",
  "Ein klarer Fokus bündelt Kräfte wie ein Laser.",
  "Sag Nein zu allem, was dich deinen Zielen nicht näher bringt.",
  "Setze Prioritäten und ziehe sie konsequent durch.",
  "Erfolg ist das Resultat täglicher kleiner Entscheidungen.",
  "Wer zwei Hasen gleichzeitig jagt, fängt keinen von beiden.",
  "Richte deine Aufmerksamkeit auf das Endergebnis.",
  "Disziplin bedeutet zu tun, was getan werden muss, auch wenn man keine Lust hat.",
  "Der Fokus bestimmt die Realität.",
  "Halte das Ziel vor Augen und die Füße auf dem Boden.",
  "Lass Ergebnisse für sich selbst sprechen.",
  "Kanalisiere deine Energie zielgerichtet.",
  "Bleib stur bei deinen Zielen, aber flexibel bei deinen Methoden.",
  "Kleine tägliche Verbesserungen summieren sich gewaltig.",
  "Wer seinen Kurs kennt, lässt sich vom Gegenwind nicht beirren.",
  "Fokus ist das Tor zur Höchstleistung.",
  "Beseitige den Lärm und konzentriere dich auf die Essenz.",
  "Präzises Handeln führt zu exakten Ergebnissen.",
  "Verliere nie die Vision aus den Augen.",
  "Lass dein Vorhaben dein einziger Maßstab sein.",
  "Räum Hindernisse systematisch aus dem Weg.",
  "Halte den Blick starr auf den Gipfel gerichtet.",
  "Lass deine Disziplin lauter sein als deine Stimmung.",
  "Kontinuität erschafft Meisterwerke.",
  "Entscheide, was wichtig ist, und ignoriere den Rest.",
  "Wer klare Ziele hat, braucht keine Motivation von außen.",
  "Arbeite hart in der Stille, lass deinen Erfolg den Lärm machen.",
  "Sei scharf wie eine Klinge in deiner Ausrichtung.",
  "Gezielter Einsatz bringt maximale Wirkung.",
  "Bleib am Ball, auch wenn die Zuschauer fehlen.",
  "Das Ziel ist nicht das Ende, sondern der Maßstab deiner Reise.",
  "Konzentration ist die Fähigkeit, im entscheidenden Moment da zu sein.",
  "Nutze jede Stunde als Schritt in die richtige Richtung.",
  "Fokussiere dich auf den Prozess, die Ergebnisse folgen automatisch.",
  "Verankere deine Ziele tief in deiner täglichen Routine.",
  "Exzellenz ist keine Handlung, sondern eine Gewohnheit.",
  "Setze den Meilenstein und marschiere los.",
  "Disziplin schützt dich vor späten Reuegefühlen.",
  "Mit klarem Blick durch jede Ablenkung.",

  // 201-250: Durchhaltevermögen & Resilienz
  "Aufgeben ist keine Option, solange du noch atmest.",
  "Stürme machen Bäume tiefer verwurzelt.",
  "Fall siebenmal um, steh achtmal auf.",
  "In der Krise zeigt sich der wahre Charakter.",
  "Aus Niederlagen werden die lehrreichsten Lektionen geboren.",
  "Niemand hat gesagt, dass es leicht wird, aber es wird sich lohnen.",
  "Schmerz ist vorübergehend, Stolz bleibt für immer.",
  "Harte Zeiten formen starke Menschen.",
  "Der tiefste Punkt ist die beste Basis für den Wiederaufbau.",
  "Wer den Berg erklimmen will, muss den Aufstieg akzeptieren.",
  "Du bist resilienter als jedes Problem vor dir.",
  "Geduld und Spucke bringen dich weiter als Hektik.",
  "Verwandle Steine im Weg in Stufen nach oben.",
  "Der Weg durch die Hölle endet nur, wenn du weitergehst.",
  "Rückschläge sind nur Anlauf für den nächsten Sprung.",
  "Ausdauer ist der beste Freund des Erfolgs.",
  "Wer im Nebel weitergeht, sieht als Erster die Sonne.",
  "Glaube an dich, wenn der Sturm am lautesten brüllt.",
  "Lass dich brechen, um stärker zusammenzuwachsen.",
  "Jede Narbe erzählt eine Geschichte von Überwindung.",
  "Halt durch! Der schwerste Abschnitt kommt oft kurz vor der Spitze.",
  "Aus Widrigkeiten wird Stärke geschmiedet.",
  "Kein Regenschauer dauert ewig.",
  "Steh deinen Mann/deine Frau, egal wie stark der Wind bläst.",
  "Es ist immer zu früh, um aufzugeben.",
  "Resilienz ist der Schild gegen den Zweifel.",
  "Was dich nicht umwirft, macht dich erfahrener.",
  "Setze deinen Weg fort, auch wenn die Beine schwer werden.",
  "Am Ende zählt, wer noch steht.",
  "Niederlagen sind nur Zwischenstationen auf dem Weg nach oben.",
  "Die stärksten Diamanten entstehen unter dem höchsten Druck.",
  "Lass dich von Rückschlägen anspornen, nicht entmutigen.",
  "Nimm den Kampf an und wachse daran.",
  "Fehler sind der Beweis dafür, dass du es versuchst.",
  "Bleib standhaft in deinen Werten und Plänen.",
  "Ein Schritt nach dem anderen – so durchquert man Wüsten.",
  "Lass die Vergangenheit ruhen und kämpfe für die Zukunft.",
  "Deine Zähigkeit entscheidet über deinen Erfolg.",
  "Gib nicht auf kurz bevor das Wunder geschieht.",
  "Überwindung ist der Schlüssel zur Freiheit.",
  "Der beste Schutz gegen Misserfolg ist stetiges Weitergehen.",
  "Zeige den Problemen, wer der Chef im Haus ist.",
  "Aus Stolpern wird Gehen, aus Gehen wird Laufen.",
  "Standfestigkeit zahlt sich immer aus.",
  "Nichts kann dich stoppen, außer deiner eigenen Entscheidung.",
  "Kraft wächst nicht aus Siegen, sondern aus Herausforderungen.",
  "Lerne zu ruhen, nicht aufzugeben, wenn du müde bist.",
  "Die tiefste Nacht gebiert den hellsten Morgen.",
  "Verwandle deine Wunden in Weisheit.",
  "Du bist ein Kämpfer, vergiss das nie.",

  // 251-300: Mindset & Einstellung
  "Glaube, dass du es kannst, und du bist schon den halben Weg dort.",
  "Deine Gedanken formen dein Schicksal.",
  "Optimismus ist eine Entscheidung, die jeden Tag neu getroffen wird.",
  "Sei dankbar für das, was ist, und mutig für das, was kommt.",
  "Ein positives Mindset findet in jedem Hindernis eine Chance.",
  "Erfolg ist die Einstellung, niemals aufzuhören zu lernen.",
  "Dein Geist ist deine stärkste Waffe – halte ihn scharf.",
  "Denke in Lösungen, nicht in Einschränkungen.",
  "Selbstvertrauen entsteht durch das Überwinden von Ängsten.",
  "Die Welt sieht so aus, wie du dich entscheidest sie zu sehen.",
  "Befreie deinen Kopf von 'Ich kann nicht'.",
  "Freue dich über Erfolge anderer und wachse selbst daran.",
  "Ein starker Verstand trägt einen müden Körper.",
  "Vertraue darauf, dass sich die Dinge zum Guten wenden, wenn du arbeitest.",
  "Wachstum beginnt am Ende deiner Komfortzone.",
  "Sei dein eigener größter Anfeuerer.",
  "Mentale Stärke erfordert tägliche Hygiene deiner Gedanken.",
  "Du bist das Ergebnis deiner habitualisierten Einstellungen.",
  "Echte Fülle beginnt im Geist.",
  "Ersetze 'Warum ich?' durch 'Versuch's doch!'.",
  "Glaube an Wunder, aber verlass dich auf deine Arbeit.",
  "Deine Perspektive verändert das komplette Spiel.",
  "Innere Ruhe gibt äußere Kraft.",
  "Sei offen für Veränderungen – sie sind der Motor des Lebens.",
  "Feiere kleine Siege auf dem Weg zum großen Ziel.",
  "Dein Wert hängt nicht von der Meinung anderer ab.",
  "Richte deinen inneren Kompass auf Erfolg und Glück.",
  "Der Verstand kreiert die Realität, in der wir leben.",
  "Sei stolz auf deine Fortschritte, egal wie klein sie scheinen.",
  "Positive Energie ziehst du durch positive Haltung an.",
  "Lerne, das Gute in jeder Situation zu sehen.",
  "Mentale Klarheit bringt physische Stärke.",
  "Mach dir bewusst, wie weit du bereits gekommen bist.",
  "Erfolg ist eine Geisteshaltung vor dem materiellen Resultat.",
  "Nimm das Leben nicht als Last, sondern als Abenteuer.",
  "Du besitzt bereits alles, was du zum Starten brauchst.",
  "Lass Dankbarkeit dein täglicher Begleiter sein.",
  "Nutze die Macht der positiven Glaubenssätze.",
  "Der Glaube an dich selbst ist der Schlüssel zu allen Türen.",
  "Transformation beginnt von innen nach außen.",
  "Wer seine Gedanken kontrolliert, kontrolliert sein Leben.",
  "Ein Lächeln öffnet mehr Wege als sture Gewalt.",
  "Gelassenheit bringt die besten Entscheidungen hervor.",
  "Denke groß, handle klug, bleibe bescheiden.",
  "Deine Haltung entscheidet über deine Flughöhe.",
  "Investiere in deinen Verstand, er zahlt die besten Zinsen.",
  "Schüttle Zweifel ab wie Regenkleidung.",
  "Nichts ist unmöglich für den, der fest daran glaubt.",
  "Sei Meister deines Geistes, nicht sein Sklave.",
  "Dein Potenzial wartet nur darauf, von dir abgerufen zu werden.",

  // 301-350: Selbstbewusstsein & Innere Stärke
  "Steh zu dem, wer du bist – das ist deine größte Superkraft.",
  "Niemand kann dir das Gefühl geben, minderwertig zu sein, ohne deine Zustimmung.",
  "Du bist einzigartig, und genau das ist deine Stärke.",
  "Verstelle dich nicht für andere, lebe deine eigene Wahrheit.",
  "Selbstliebe ist das Fundament für jedes Wachstum.",
  "Du brauchst keine Erlaubnis, um großartig zu sein.",
  "Sei stolz auf deine Narben, sie zeigen deinen Siegeszug.",
  "Vertraue deinen Fähigkeiten, du hast schon vieles gemeistert.",
  "Lass dein Licht strahlen, ohne dich zu entschuldigen.",
  "Du bist stark genug, um jeden Sturm zu überstehen.",
  "Steh aufrecht und schau der Welt direkt in die Augen.",
  "Lass nicht zu, dass fremde Erwartungen dein Leben diktieren.",
  "In deiner Verletzlichkeit liegt deine wahre Stärke.",
  "Sei das Original, nicht die Kopie eines anderen.",
  "Du bist wertvoll, genau so wie du jetzt gerade bist.",
  "Glaube an deine eigene Stimme, auch wenn sie zittert.",
  "Gib dir selbst den Respekt, den du anderen entgegenbringst.",
  "Deine Grenzen bestimmst ganz alleine du.",
  "Mache dein Glück nicht von externer Bestätigung abhängig.",
  "Sei mutig genug, deinen eigenen Weg zu gehen.",
  "Du bist der Schöpfer deines eigenen Schicksals.",
  "Steh zu deinen Fehlern, sie machen dich menschlich und stark.",
  "Erkenne deinen eigenen Wert und fordere ihn ein.",
  "Nimm deinen Platz in der Welt voller Stolz ein.",
  "Lass dich nicht von Neidern verunsichern.",
  "Innere Stärke zeigt sich in ruhiger Entschlossenheit.",
  "Sei dir selbst der beste Freund und wichtigste Verbündete.",
  "Trau deinen Entscheidungen und steh dazu.",
  "Du bist kein Produkt deiner Umstände, sondern deiner Entscheidungen.",
  "Vertraue deinem Bauchgefühl – es täuscht dich selten.",
  "Achte auf deine eigenen Bedürfnisse mit der gleichen Sorge.",
  "Selbstachtung ist unbezahlbar.",
  "Sei dein eigener Fels in der Brandung.",
  "Lass dich nicht von Zweiflern leise machen.",
  "Deine Existenz ist eine Bereicherung für die Welt.",
  "Sei stolz auf deine Eigenarten – sie machen dich aus.",
  "Nimm dir das Recht heraus, Nein zu sagen.",
  "Du bist stärker als deine Ängste.",
  "Lerne dich selbst kennen und du wirst unbesiegt bleiben.",
  "Anerkennung beginnt bei dir selbst.",
  "Steh für deine Überzeugungen ein, auch wenn du alleine stehst.",
  "Deine innere Flamme kann von niemandem gelöscht werden.",
  "Erlaube dir, Raum einzunehmen.",
  "Deine Geschichte ist es wert, erzählt zu werden.",
  "Vertraue deinem Weg, auch wenn er ungewöhnlich erscheint.",
  "Lass deine Taten von Selbstvertrauen geprägt sein.",
  "Gib niemals deine Integrität für schnelle Vorteile auf.",
  "Du bist ein Unikat auf dieser Erde.",
  "In dir ruht eine unerschöpfliche Quelle von Mut.",
  "Sei der Held deiner eigenen Geschichte.",

  // 351-400: Erfolg & Leistung
  "Erfolg ist die Summe kleiner Anstrengungen, die sich täglich wiederholen.",
  "Wer Höchstleistungen erbringen will, muss exzellent vorbereitet sein.",
  "Erfolg kommt nicht zu dir – du musst zu ihm gehen.",
  "Messe deinen Erfolg an den Hindernissen, die du überwunden hast.",
  "Harte Arbeit schlägt Talent, wenn Talent nicht hart arbeitet.",
  "Der Preis des Erfolgs ist Hingabe und unermüdlicher Einsatz.",
  "Erfolg ist kein Zufall, sondern das Ergebnis von Strategie und Fleiß.",
  "Setze dir Standards, keine Limits.",
  "Spitzenleistung ist eine Frage der ständigen Vorbereitung.",
  "Erfolg bedeutet, einmal mehr aufzustehen als man umgeworfen wurde.",
  "Wer Großes erreichen will, muss Großen Einsatz zeigen.",
  "Bringe Opfer für deine Träume, sonst werden deine Träume zum Opfer.",
  "Qualität ist kein Zufall, sie ist immer das Ergebnis hoher Absichten.",
  "Die Früchte des Erfolgs schmecken am besten nach hartem Kampf.",
  "Erfolg erfordert Fokus, Opferbereitschaft und Ausdauer.",
  "Strebe nach Exzellenz in allem, was du tust.",
  "Gewinner suchen Wege, Verlierer suchen Ausreden.",
  "Nutze deine Zeit produktiv, sie ist deine wertvollste Ressource.",
  "Meisterschaft erfordert jahrelanges, fokussiertes Üben.",
  "Erfolg ist der beste Beweis für die Richtigkeit deines Weges.",
  "Lass deinen Erfolg deine lauteste Antwort sein.",
  "Verdiene dir deinen Erfolg mit Schweiß und Entschlossenheit.",
  "Überflügel deine eigenen Rekorde täglich.",
  "Erfolg ist eine Reise, kein Zielort.",
  "Lerne die Spielregeln und spiele besser als jeder andere.",
  "Konkurriere nur mit deinem gestrigen Ich.",
  "Wer Spitzenleistungen will, muss Spitzenaufwand betreiben.",
  "Die Meile der Extra-Anstrengung ist nie überfüllt.",
  "Erfolg wächst auf dem Boden von Disziplin und Haltung.",
  "Setze alles auf eine Karte und arbeite hart dafür.",
  "Echter Erfolg bringt andere Menschen mit nach oben.",
  "Sei unermüdlich in deiner Jagd nach Fortschritt.",
  "Lass dich nicht durch frühe Siege träge machen.",
  "Höchstleistung entsteht unter klarem Fokus.",
  "Erfolg belohnt die Fleißigen und Mutigen.",
  "Wer Säen will, muss die Felder bestellen.",
  "Erfolge fallen nicht vom Himmel, sie werden erarbeitet.",
  "Mache Exzellenz zu deiner persönlichen Norm.",
  "Der Unterschied zwischen Gut und Großartig ist die Liebe zum Detail.",
  "Lass deinen Siegeswillen größer sein als die Angst zu scheitern.",
  "Wer seinen Preis zahlt, wird belohnt werden.",
  "Erfolg erfordert klare Entscheidungen und mutiges Handeln.",
  "Baue dein Imperium Stein für Stein auf.",
  "Meistere das Fundament, bevor du die Krone anstrebst.",
  "Dein Erfolg inspirierte mehr Menschen als du ahnst.",
  "Bleib bescheiden im Erfolg und stark im Rückschlag.",
  "Mache deine Ambitionen zu Realität.",
  "Leistung wird durch kontinuierliche Mühe geformt.",
  "Feiere den Erfolg, aber bleibe hungrig nach mehr.",
  "Erfolg ist die Belohnung für Stehvermögen.",

  // 401-450: Mut & Durchbruch
  "Verlasse den sicheren Hafen – Abenteuer warten auf hoher See.",
  "Mut steht am Anfang des Handelns, Glück am Ende.",
  "Trau dich, den ersten Schritt ins Unbekannte zu machen.",
  "Breche die Ketten deiner Zweifel und fliege.",
  "Das Leben beginnt dort, wo deine Angst endet.",
  "Sei mutig genug, eine neue Tür zu öffnen.",
  "Der Durchbruch kommt oft direkt nach dem größten Widerstand.",
  "Riskiere etwas – ohne Risiko gibt es keine Belohnung.",
  "Spring und das Netz wird sich weben.",
  "Hör auf, auf Erlaubnis zu warten – starte einfach!",
  "Mut ist der Schlüssel zu allen verschlossenen Türen.",
  "Wer nicht wagt, der nicht gewinnt.",
  "Die größten Entdeckungen lagen nie auf ausgetretenen Pfaden.",
  "Mach den Sprung und vertraue deinen Flügeln.",
  "Lass deinen Mut größer sein als deine Bequemlichkeit.",
  "Herausforderungen sind Gelegenheiten für Helden.",
  "Bringe das Eis zum Schmelzen durch mutiges Handeln.",
  "Trau dich, deine Stimme laut zu erheben.",
  "Der Durchbruch erfordert maximale Intensität im richtigen Moment.",
  "Sei der Pionier deines eigenen Lebens.",
  "Fürchte dich nicht vor Veränderung, umarme sie.",
  "Mut wächst mit jedem Schritt, den du machst.",
  "Greife nach den Gelegenheiten, wenn sie sich bieten.",
  "Nimm dein Schicksal furchtlos in die Hand.",
  "Sprungentscheidungen verändern oft ganze Leben.",
  "Setze alles daran, Barrieren niederzureißen.",
  "Beweise dir selbst, wozu du fähig bist.",
  "Trau dich, deine Träume laut auszusprechen.",
  "Kein Sieg ohne mutigen Einsatz.",
  "Sei ein Wegbereiter, kein Mitläufer.",
  "Überwinde die Hürden in deinem Geist.",
  "Durchbrüche entstehen durch unnachgiebigen Druck.",
  "Sei entschlossen, deine Träume wahr werden zu lassen.",
  "Hab keine Angst vor großen Sprüngen – zwei kleine Abgründe überwindet man nicht.",
  "Mutig zu sein heißt nicht, keine Angst zu haben, sondern es trotzdem zu tun.",
  "Stürze dich ins Abenteuer des Lebens.",
  "Jede große Reise beginnt mit einem mutigen Entschluss.",
  "Renne auf deine Ängste zu – sie lösen sich auf.",
  "Sei kühn in deiner Planung und mutig in der Umsetzung.",
  "Schaffe Fakten durch mutige Entscheidungen.",
  "Lass dich nicht von Sicherheit lähmen.",
  "Der Durchbruch ist nur eine Entscheidung entfernt.",
  "Geh dorthin, wo noch niemand war, und hinterlasse eine Spur.",
  "Setze dein Segel gegen den stärksten Wind.",
  "Furchtlosigkeit ist die Frucht regelmäßigen Mut-Trainings.",
  "Zögere nicht lang – handle entschlossen.",
  "Nimm die Herausforderung an und fordere das Schicksal heraus.",
  "Dein Mut bestimmt das Ausmaß deiner Freiheit.",
  "Spring über deinen eigenen Schatten.",
  "Ergreife die Initiative und gestalte die Welt.",

  // 451-500: Inspiration & Visionen
  "Lass deine Vision deine tägliche Motivation sein.",
  "Die Welt braucht das Licht, das nur du ausstrahlen kannst.",
  "Inspiriere andere durch dein Vorbild, nicht nur durch Worte.",
  "Wer eine klare Vision hat, findet immer einen Weg.",
  "Träume nicht dein Leben, sondern lebe deinen Traum.",
  "Deine Zukunft wird durch das gestaltet, was du heute tust.",
  "Sei eine Quelle der Hoffnung und der positiven Energie.",
  "Blicke über den Horizont hinaus auf das, was möglich ist.",
  "Große Visionen erfordern Ausdauer und Herzblut.",
  "Lass dich von der Zukunft anziehen, statt von der Vergangenheit halten.",
  "Deine Taten heute sind die Samen für die Ernte von morgen.",
  "Schaffe etwas, das über dich hinausbesteht.",
  "Ein inspirierter Geist bewegt Berge.",
  "Glaube an die unendlichen Möglichkeiten des Universums.",
  "Lebe so, dass dein Leben ein Kunstwerk wird.",
  "Setze Zeichen, die lange nachwirken.",
  "Bringe deine innere Fülle in die Welt ein.",
  "Deine Vision ist der Kompass auf deiner Lebensreise.",
  "Erschaffe Werte, die bleiben.",
  "Gib der Welt das Beste, was du zu bieten hast.",
  "Inspiration ist überall, du musst nur dein Herz öffnen.",
  "Lass deine Ziele so groß sein, dass sie dich morgens aus dem Bett katapultieren.",
  "Du bist ein Gestalter der Zukunft.",
  "Verwurzelt in der Gegenwart, den Blick in die Zukunft gerichtet.",
  "Verwandle Inspiration in greifbare Realität.",
  "Sei das Vorbild, das du dir früher gewünscht hättest.",
  "Visionäre lassen sich von kurzfristigen Hürden nicht ablenken.",
  "Mach deinen Lebensweg zu einer inspirierenden Reise.",
  "Dein Traum verdient deinen vollen Einsatz.",
  "Trage Zuversicht in die Herzen anderer Menschen.",
  "Wer die Sterne erreichen will, darf den Blick nicht auf den Boden richten.",
  "Lass deine Vision lebendig und greifbar werden.",
  "Das Leben ist zu kurz für kleine Träume.",
  "Bringe deine Talente voll zur Entfaltung.",
  "Lass deine Leidenschaft das Fundament deiner Vision sein.",
  "Echte Inspiration führt immer zu konkretem Handeln.",
  "Baue Brücken in eine bessere Zukunft.",
  "Deine Vision verleiht deinem Alltag tiefen Sinn.",
  "Bleib der großen Idee treu.",
  "Forme die Welt nach deinen positiven Vorstellungen.",
  "Jede große Veränderung begann mit einer einzelnen Vision.",
  "Lass dich nicht von Bedenkenträgern bremsen.",
  "Inspiriere deine Umwelt durch exzellente Ergebnisse.",
  "Geh deinen Weg voller Anmut und Stärke.",
  "Dein Beitrag zählt – unterschätze ihn niemals.",
  "Blicke mit Vorfreude auf das, was du noch erschaffen wirst.",
  "Du bist der Schöpfer deiner nächsten großen Etappe.",
  "Entfache das Feuer in dir und leuchte hell.",
  "Vision plus Aktion ergibt unaufhaltsame Transformation.",
  "Dein Weg ist das Ziel – genieße jeden Schritt voller Motivation!"
];

// Funktion zum Abrufen eines zufälligen Spruchs aus der statischen Liste
function getRandomSpruch() {
  const index = Math.floor(Math.random() * sprueche.length);
  return sprueche[index];
}